// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lake.proto

package lakepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- 两级 ref(P4.2) ---
type RefKind int32

const (
	RefKind_REF_KIND_UNSPECIFIED RefKind = 0
	RefKind_REQUEST              RefKind = 1 // 请求持有
	RefKind_IN_FLIGHT            RefKind = 2 // 在途传输
	RefKind_WRITEBACK            RefKind = 3 // 写回未 durable ack
)

// Enum value maps for RefKind.
var (
	RefKind_name = map[int32]string{
		0: "REF_KIND_UNSPECIFIED",
		1: "REQUEST",
		2: "IN_FLIGHT",
		3: "WRITEBACK",
	}
	RefKind_value = map[string]int32{
		"REF_KIND_UNSPECIFIED": 0,
		"REQUEST":              1,
		"IN_FLIGHT":            2,
		"WRITEBACK":            3,
	}
)

func (x RefKind) Enum() *RefKind {
	p := new(RefKind)
	*p = x
	return p
}

func (x RefKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lake_proto_enumTypes[0].Descriptor()
}

func (RefKind) Type() protoreflect.EnumType {
	return &file_lake_proto_enumTypes[0]
}

func (x RefKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefKind.Descriptor instead.
func (RefKind) EnumDescriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{0}
}

type PullPolicy int32

const (
	PullPolicy_PULL_BEST_EFFORT   PullPolicy = 0 // 传多少算多少,可中断
	PullPolicy_PULL_WAIT_COMPLETE PullPolicy = 1 // 传完才返回
	PullPolicy_PULL_TIMEOUT       PullPolicy = 2 // 超预算即停,返回已传
)

// Enum value maps for PullPolicy.
var (
	PullPolicy_name = map[int32]string{
		0: "PULL_BEST_EFFORT",
		1: "PULL_WAIT_COMPLETE",
		2: "PULL_TIMEOUT",
	}
	PullPolicy_value = map[string]int32{
		"PULL_BEST_EFFORT":   0,
		"PULL_WAIT_COMPLETE": 1,
		"PULL_TIMEOUT":       2,
	}
)

func (x PullPolicy) Enum() *PullPolicy {
	p := new(PullPolicy)
	*p = x
	return p
}

func (x PullPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_lake_proto_enumTypes[1].Descriptor()
}

func (PullPolicy) Type() protoreflect.EnumType {
	return &file_lake_proto_enumTypes[1]
}

func (x PullPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPolicy.Descriptor instead.
func (PullPolicy) EnumDescriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{1}
}

type ViewEvent_Kind int32

const (
	ViewEvent_REGISTERED  ViewEvent_Kind = 0
	ViewEvent_INVALIDATED ViewEvent_Kind = 1
	ViewEvent_MOVED       ViewEvent_Kind = 2
)

// Enum value maps for ViewEvent_Kind.
var (
	ViewEvent_Kind_name = map[int32]string{
		0: "REGISTERED",
		1: "INVALIDATED",
		2: "MOVED",
	}
	ViewEvent_Kind_value = map[string]int32{
		"REGISTERED":  0,
		"INVALIDATED": 1,
		"MOVED":       2,
	}
)

func (x ViewEvent_Kind) Enum() *ViewEvent_Kind {
	p := new(ViewEvent_Kind)
	*p = x
	return p
}

func (x ViewEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_lake_proto_enumTypes[2].Descriptor()
}

func (ViewEvent_Kind) Type() protoreflect.EnumType {
	return &file_lake_proto_enumTypes[2]
}

func (x ViewEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewEvent_Kind.Descriptor instead.
func (ViewEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{2, 0}
}

type LeaseHeartbeat_Op int32

const (
	LeaseHeartbeat_MOUNT     LeaseHeartbeat_Op = 0
	LeaseHeartbeat_UNMOUNT   LeaseHeartbeat_Op = 1
	LeaseHeartbeat_KEEPALIVE LeaseHeartbeat_Op = 2
)

// Enum value maps for LeaseHeartbeat_Op.
var (
	LeaseHeartbeat_Op_name = map[int32]string{
		0: "MOUNT",
		1: "UNMOUNT",
		2: "KEEPALIVE",
	}
	LeaseHeartbeat_Op_value = map[string]int32{
		"MOUNT":     0,
		"UNMOUNT":   1,
		"KEEPALIVE": 2,
	}
)

func (x LeaseHeartbeat_Op) Enum() *LeaseHeartbeat_Op {
	p := new(LeaseHeartbeat_Op)
	*p = x
	return p
}

func (x LeaseHeartbeat_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseHeartbeat_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_lake_proto_enumTypes[3].Descriptor()
}

func (LeaseHeartbeat_Op) Type() protoreflect.EnumType {
	return &file_lake_proto_enumTypes[3]
}

func (x LeaseHeartbeat_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseHeartbeat_Op.Descriptor instead.
func (LeaseHeartbeat_Op) EnumDescriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{11, 0}
}

type TransferStatusResponse_State int32

const (
	TransferStatusResponse_PENDING   TransferStatusResponse_State = 0
	TransferStatusResponse_IN_FLIGHT TransferStatusResponse_State = 1
	TransferStatusResponse_DONE      TransferStatusResponse_State = 2
	TransferStatusResponse_FAILED    TransferStatusResponse_State = 3
)

// Enum value maps for TransferStatusResponse_State.
var (
	TransferStatusResponse_State_name = map[int32]string{
		0: "PENDING",
		1: "IN_FLIGHT",
		2: "DONE",
		3: "FAILED",
	}
	TransferStatusResponse_State_value = map[string]int32{
		"PENDING":   0,
		"IN_FLIGHT": 1,
		"DONE":      2,
		"FAILED":    3,
	}
)

func (x TransferStatusResponse_State) Enum() *TransferStatusResponse_State {
	p := new(TransferStatusResponse_State)
	*p = x
	return p
}

func (x TransferStatusResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatusResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_lake_proto_enumTypes[4].Descriptor()
}

func (TransferStatusResponse_State) Type() protoreflect.EnumType {
	return &file_lake_proto_enumTypes[4]
}

func (x TransferStatusResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatusResponse_State.Descriptor instead.
func (TransferStatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{20, 0}
}

// --- 订阅视图(边3/4) ---
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`       // Router 实例 / agent 实例
	ResumeFromSeq uint64                 `protobuf:"varint,2,opt,name=resume_from_seq,json=resumeFromSeq,proto3" json:"resume_from_seq,omitempty"` // 断线重连:"resume from seq N"(见 control-plane.md「粒度与协议」)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_lake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetResumeFromSeq() uint64 {
	if x != nil {
		return x.ResumeFromSeq
	}
	return 0
}

type ViewUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`      // 单流序号(单权威退化为单 publisher)
	Events        []*ViewEvent           `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"` // 增量事件(block 注册/失效/迁移)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewUpdate) Reset() {
	*x = ViewUpdate{}
	mi := &file_lake_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUpdate) ProtoMessage() {}

func (x *ViewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUpdate.ProtoReflect.Descriptor instead.
func (*ViewUpdate) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{1}
}

func (x *ViewUpdate) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ViewUpdate) GetEvents() []*ViewEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ViewEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ViewEvent_Kind         `protobuf:"varint,1,opt,name=kind,proto3,enum=lake.ViewEvent_Kind" json:"kind,omitempty"`
	Id            *KVBlockID             `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                     // 变更的 block
	Locations     []*Location            `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`                                       // 变更后的 L0/L1/L2 位置(增量)
	L3Present     bool                   `protobuf:"varint,4,opt,name=l3_present,json=l3Present,proto3" json:"l3_present,omitempty"`                     // L3 存在性变更(MOVED/REGISTERED 带上)
	BlockKind     BlockKind              `protobuf:"varint,5,opt,name=block_kind,json=blockKind,proto3,enum=lake.BlockKind" json:"block_kind,omitempty"` // 仅 REGISTERED 首次带上,后续 MOVED 不重复
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewEvent) Reset() {
	*x = ViewEvent{}
	mi := &file_lake_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEvent) ProtoMessage() {}

func (x *ViewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEvent.ProtoReflect.Descriptor instead.
func (*ViewEvent) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{2}
}

func (x *ViewEvent) GetKind() ViewEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return ViewEvent_REGISTERED
}

func (x *ViewEvent) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ViewEvent) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ViewEvent) GetL3Present() bool {
	if x != nil {
		return x.L3Present
	}
	return false
}

func (x *ViewEvent) GetBlockKind() BlockKind {
	if x != nil {
		return x.BlockKind
	}
	return BlockKind_KIND_UNSPECIFIED
}

// --- LookupPrefix(Router 选路) ---
type LookupPrefixRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelId         string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	PrefixHashes    [][]byte               `protobuf:"bytes,2,rep,name=prefix_hashes,json=prefixHashes,proto3" json:"prefix_hashes,omitempty"`            // 前缀 block hash 链(沿 radix 匹配)
	RequesterNodeId string                 `protobuf:"bytes,3,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"` // 判定 local_hit 用
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LookupPrefixRequest) Reset() {
	*x = LookupPrefixRequest{}
	mi := &file_lake_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPrefixRequest) ProtoMessage() {}

func (x *LookupPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPrefixRequest.ProtoReflect.Descriptor instead.
func (*LookupPrefixRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{3}
}

func (x *LookupPrefixRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LookupPrefixRequest) GetPrefixHashes() [][]byte {
	if x != nil {
		return x.PrefixHashes
	}
	return nil
}

func (x *LookupPrefixRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type LookupPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*ReusableBlock       `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`                                 // 沿前缀匹配的连续 block 列表
	HitLength     uint32                 `protobuf:"varint,2,opt,name=hit_length,json=hitLength,proto3" json:"hit_length,omitempty"`         // 命中到第几个 block(仿 SGLang host_hit_length)
	AllLocalHit   bool                   `protobuf:"varint,3,opt,name=all_local_hit,json=allLocalHit,proto3" json:"all_local_hit,omitempty"` // 全在 requester HBM → D-direct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupPrefixResponse) Reset() {
	*x = LookupPrefixResponse{}
	mi := &file_lake_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupPrefixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupPrefixResponse) ProtoMessage() {}

func (x *LookupPrefixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupPrefixResponse.ProtoReflect.Descriptor instead.
func (*LookupPrefixResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{4}
}

func (x *LookupPrefixResponse) GetBlocks() []*ReusableBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *LookupPrefixResponse) GetHitLength() uint32 {
	if x != nil {
		return x.HitLength
	}
	return 0
}

func (x *LookupPrefixResponse) GetAllLocalHit() bool {
	if x != nil {
		return x.AllLocalHit
	}
	return false
}

type ReusableBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KVBlockID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Meta          *BlockMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	LocalHit      bool                   `protobuf:"varint,3,opt,name=local_hit,json=localHit,proto3" json:"local_hit,omitempty"` // 该 block 已在 requester HBM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReusableBlock) Reset() {
	*x = ReusableBlock{}
	mi := &file_lake_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReusableBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReusableBlock) ProtoMessage() {}

func (x *ReusableBlock) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReusableBlock.ProtoReflect.Descriptor instead.
func (*ReusableBlock) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{5}
}

func (x *ReusableBlock) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ReusableBlock) GetMeta() *BlockMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReusableBlock) GetLocalHit() bool {
	if x != nil {
		return x.LocalHit
	}
	return false
}

// --- Locate(agent 搬 KV 查权威) ---
type LocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*KVBlockID           `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateRequest) Reset() {
	*x = LocateRequest{}
	mi := &file_lake_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateRequest) ProtoMessage() {}

func (x *LocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateRequest.ProtoReflect.Descriptor instead.
func (*LocateRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{6}
}

func (x *LocateRequest) GetIds() []*KVBlockID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type LocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*BlockMeta           `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocateResponse) Reset() {
	*x = LocateResponse{}
	mi := &file_lake_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateResponse) ProtoMessage() {}

func (x *LocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateResponse.ProtoReflect.Descriptor instead.
func (*LocateResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{7}
}

func (x *LocateResponse) GetBlocks() []*BlockMeta {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// --- 满块注册 ---
type RegisterBlocksRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Blocks []*BlockMeta           `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"` // agent 写完 L2 durable 后上报(单次=PutEnd,见上方 RPC 注释)
	// P4.2:完整有序前缀 hash 链(与 LookupPrefix.prefix_hashes 同形)。
	//
	//	`blocks` 可以是 miss 后缀;控制面用本字段 root/extend 建 lineage。
	PrefixHashes  [][]byte `protobuf:"bytes,3,rep,name=prefix_hashes,json=prefixHashes,proto3" json:"prefix_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBlocksRequest) Reset() {
	*x = RegisterBlocksRequest{}
	mi := &file_lake_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBlocksRequest) ProtoMessage() {}

func (x *RegisterBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBlocksRequest.ProtoReflect.Descriptor instead.
func (*RegisterBlocksRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterBlocksRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterBlocksRequest) GetBlocks() []*BlockMeta {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *RegisterBlocksRequest) GetPrefixHashes() [][]byte {
	if x != nil {
		return x.PrefixHashes
	}
	return nil
}

type RefDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KVBlockID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          RefKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=lake.RefKind" json:"kind,omitempty"`
	Delta         int32                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"` // +1 / -1(允许多)
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefDelta) Reset() {
	*x = RefDelta{}
	mi := &file_lake_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefDelta) ProtoMessage() {}

func (x *RefDelta) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefDelta.ProtoReflect.Descriptor instead.
func (*RefDelta) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{9}
}

func (x *RefDelta) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RefDelta) GetKind() RefKind {
	if x != nil {
		return x.Kind
	}
	return RefKind_REF_KIND_UNSPECIFIED
}

func (x *RefDelta) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *RefDelta) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// --- 请求屏障 ---
type RequestBarrierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBarrierRequest) Reset() {
	*x = RequestBarrierRequest{}
	mi := &file_lake_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBarrierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBarrierRequest) ProtoMessage() {}

func (x *RequestBarrierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBarrierRequest.ProtoReflect.Descriptor instead.
func (*RequestBarrierRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{10}
}

func (x *RequestBarrierRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestBarrierRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// --- lease ---
type LeaseHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            LeaseHeartbeat_Op      `protobuf:"varint,1,opt,name=op,proto3,enum=lake.LeaseHeartbeat_Op" json:"op,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SegmentId     uint64                 `protobuf:"varint,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // 挂摘的段
	SegmentLen    uint64                 `protobuf:"varint,4,opt,name=segment_len,json=segmentLen,proto3" json:"segment_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseHeartbeat) Reset() {
	*x = LeaseHeartbeat{}
	mi := &file_lake_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseHeartbeat) ProtoMessage() {}

func (x *LeaseHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseHeartbeat.ProtoReflect.Descriptor instead.
func (*LeaseHeartbeat) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{11}
}

func (x *LeaseHeartbeat) GetOp() LeaseHeartbeat_Op {
	if x != nil {
		return x.Op
	}
	return LeaseHeartbeat_MOUNT
}

func (x *LeaseHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LeaseHeartbeat) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *LeaseHeartbeat) GetSegmentLen() uint64 {
	if x != nil {
		return x.SegmentLen
	}
	return 0
}

type LeaseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	TtlMs         uint64                 `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseAck) Reset() {
	*x = LeaseAck{}
	mi := &file_lake_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseAck) ProtoMessage() {}

func (x *LeaseAck) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseAck.ProtoReflect.Descriptor instead.
func (*LeaseAck) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{12}
}

func (x *LeaseAck) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *LeaseAck) GetTtlMs() uint64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

// --- Dispatch(边10 调度指令) ---
type DispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // PD_SEPARATED | COLOCATED | D_DIRECT
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	ReuseBlocks   []*KVBlockID           `protobuf:"bytes,3,rep,name=reuse_blocks,json=reuseBlocks,proto3" json:"reuse_blocks,omitempty"`
	Hints         map[string]string      `protobuf:"bytes,4,rep,name=hints,proto3" json:"hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // agent_hints/kv_hints(与 #13 透传对齐)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	mi := &file_lake_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{13}
}

func (x *DispatchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DispatchRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *DispatchRequest) GetReuseBlocks() []*KVBlockID {
	if x != nil {
		return x.ReuseBlocks
	}
	return nil
}

func (x *DispatchRequest) GetHints() map[string]string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type LoadReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	QueueLen      uint32                 `protobuf:"varint,2,opt,name=queue_len,json=queueLen,proto3" json:"queue_len,omitempty"`
	InFlight      uint32                 `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	RemainingCap  uint32                 `protobuf:"varint,4,opt,name=remaining_cap,json=remainingCap,proto3" json:"remaining_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadReport) Reset() {
	*x = LoadReport{}
	mi := &file_lake_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReport) ProtoMessage() {}

func (x *LoadReport) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReport.ProtoReflect.Descriptor instead.
func (*LoadReport) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{14}
}

func (x *LoadReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LoadReport) GetQueueLen() uint32 {
	if x != nil {
		return x.QueueLen
	}
	return 0
}

func (x *LoadReport) GetInFlight() uint32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *LoadReport) GetRemainingCap() uint32 {
	if x != nil {
		return x.RemainingCap
	}
	return 0
}

// --- PlaceBlocks(补拉放置) ---
type PlaceBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*KVBlockID           `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // 放到哪个节点 HBM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBlocksRequest) Reset() {
	*x = PlaceBlocksRequest{}
	mi := &file_lake_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBlocksRequest) ProtoMessage() {}

func (x *PlaceBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBlocksRequest.ProtoReflect.Descriptor instead.
func (*PlaceBlocksRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{15}
}

func (x *PlaceBlocksRequest) GetIds() []*KVBlockID {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *PlaceBlocksRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

// --- 传输(边7/8 控制信令) ---
type TransferBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reqs          []*TransferRequest     `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBatchRequest) Reset() {
	*x = TransferBatchRequest{}
	mi := &file_lake_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBatchRequest) ProtoMessage() {}

func (x *TransferBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBatchRequest.ProtoReflect.Descriptor instead.
func (*TransferBatchRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{16}
}

func (x *TransferBatchRequest) GetReqs() []*TransferRequest {
	if x != nil {
		return x.Reqs
	}
	return nil
}

type TransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          *Location              `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                                             // 源位置(L0/L1/L2 段式)
	TargetSegmentId uint64                 `protobuf:"varint,2,opt,name=target_segment_id,json=targetSegmentId,proto3" json:"target_segment_id,omitempty"` // 目标段
	TargetOffset    uint64                 `protobuf:"varint,3,opt,name=target_offset,json=targetOffset,proto3" json:"target_offset,omitempty"`
	Length          uint64                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_lake_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{17}
}

func (x *TransferRequest) GetSource() *Location {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TransferRequest) GetTargetSegmentId() uint64 {
	if x != nil {
		return x.TargetSegmentId
	}
	return 0
}

func (x *TransferRequest) GetTargetOffset() uint64 {
	if x != nil {
		return x.TargetOffset
	}
	return 0
}

func (x *TransferRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type TransferBatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBatchAck) Reset() {
	*x = TransferBatchAck{}
	mi := &file_lake_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBatchAck) ProtoMessage() {}

func (x *TransferBatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBatchAck.ProtoReflect.Descriptor instead.
func (*TransferBatchAck) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{18}
}

func (x *TransferBatchAck) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

type TransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStatusRequest) Reset() {
	*x = TransferStatusRequest{}
	mi := &file_lake_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusRequest) ProtoMessage() {}

func (x *TransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusRequest.ProtoReflect.Descriptor instead.
func (*TransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{19}
}

func (x *TransferStatusRequest) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *TransferStatusRequest) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type TransferStatusResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	State         TransferStatusResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=lake.TransferStatusResponse_State" json:"state,omitempty"`
	BytesDone     uint64                       `protobuf:"varint,2,opt,name=bytes_done,json=bytesDone,proto3" json:"bytes_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferStatusResponse) Reset() {
	*x = TransferStatusResponse{}
	mi := &file_lake_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStatusResponse) ProtoMessage() {}

func (x *TransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStatusResponse.ProtoReflect.Descriptor instead.
func (*TransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{20}
}

func (x *TransferStatusResponse) GetState() TransferStatusResponse_State {
	if x != nil {
		return x.State
	}
	return TransferStatusResponse_PENDING
}

func (x *TransferStatusResponse) GetBytesDone() uint64 {
	if x != nil {
		return x.BytesDone
	}
	return 0
}

// --- Pull / Publish(引擎契约) ---
type PullRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ids             []*KVBlockID           `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Policy          PullPolicy             `protobuf:"varint,2,opt,name=policy,proto3,enum=lake.PullPolicy" json:"policy,omitempty"` // 仿 SGLang can_terminate_prefetch 三策略
	BudgetMs        uint32                 `protobuf:"varint,3,opt,name=budget_ms,json=budgetMs,proto3" json:"budget_ms,omitempty"`  // 超时预算(仿 SGLang base + per_ki_token)
	RequesterNodeId string                 `protobuf:"bytes,4,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_lake_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{21}
}

func (x *PullRequest) GetIds() []*KVBlockID {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *PullRequest) GetPolicy() PullPolicy {
	if x != nil {
		return x.Policy
	}
	return PullPolicy_PULL_BEST_EFFORT
}

func (x *PullRequest) GetBudgetMs() uint32 {
	if x != nil {
		return x.BudgetMs
	}
	return 0
}

func (x *PullRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type PullResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle,omitempty"`                                 // agent wait ready 用
	PulledLength  uint32                 `protobuf:"varint,2,opt,name=pulled_length,json=pulledLength,proto3" json:"pulled_length,omitempty"` // 实际拉到的 block 数
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_lake_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{22}
}

func (x *PullResponse) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *PullResponse) GetPulledLength() uint32 {
	if x != nil {
		return x.PulledLength
	}
	return 0
}

func (x *PullResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*LayerSlice          `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"` // 逐层增量(page_first_direct),非整块
	Seq           uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`      // 仿 SGLang on_publish(seq) overlap fence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_lake_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{23}
}

func (x *PublishRequest) GetSlices() []*LayerSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *PublishRequest) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type LayerSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KVBlockID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LayerIdx      uint32                 `protobuf:"varint,2,opt,name=layer_idx,json=layerIdx,proto3" json:"layer_idx,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerSlice) Reset() {
	*x = LayerSlice{}
	mi := &file_lake_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerSlice) ProtoMessage() {}

func (x *LayerSlice) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerSlice.ProtoReflect.Descriptor instead.
func (*LayerSlice) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{24}
}

func (x *LayerSlice) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LayerSlice) GetLayerIdx() uint32 {
	if x != nil {
		return x.LayerIdx
	}
	return 0
}

func (x *LayerSlice) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LayerSlice) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// --- 通用 ---
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_lake_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{25}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PutBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Blocks        []*OpaqueBlock         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlocksRequest) Reset() {
	*x = PutBlocksRequest{}
	mi := &file_lake_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlocksRequest) ProtoMessage() {}

func (x *PutBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlocksRequest.ProtoReflect.Descriptor instead.
func (*PutBlocksRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{26}
}

func (x *PutBlocksRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PutBlocksRequest) GetBlocks() []*OpaqueBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type OpaqueBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KVBlockID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 不透明 KV 字节(mock;生产为 GPU tensor 经 RDMA)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueBlock) Reset() {
	*x = OpaqueBlock{}
	mi := &file_lake_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueBlock) ProtoMessage() {}

func (x *OpaqueBlock) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueBlock.ProtoReflect.Descriptor instead.
func (*OpaqueBlock) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{27}
}

func (x *OpaqueBlock) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *OpaqueBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*KVBlockID           `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_lake_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{28}
}

func (x *GetBlocksRequest) GetIds() []*KVBlockID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*OpaqueBlock         `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"` // 缺失的 id 不出现在列表中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_lake_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{29}
}

func (x *GetBlocksResponse) GetBlocks() []*OpaqueBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GenerateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelId         string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	PromptTokens    []uint32               `protobuf:"varint,3,rep,packed,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`    // 已 tokenize 的 prompt(P3 跳过真实 tokenizer)
	MaxNewTokens    uint32                 `protobuf:"varint,4,opt,name=max_new_tokens,json=maxNewTokens,proto3" json:"max_new_tokens,omitempty"`         // mock decode 长度
	RequesterNodeId string                 `protobuf:"bytes,5,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"` // LookupPrefix local_hit 判定
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_lake_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{30}
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GenerateRequest) GetPromptTokens() []uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return nil
}

func (x *GenerateRequest) GetMaxNewTokens() uint32 {
	if x != nil {
		return x.MaxNewTokens
	}
	return 0
}

func (x *GenerateRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OutputTokens  []uint32               `protobuf:"varint,2,rep,packed,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReusedBlocks  uint32                 `protobuf:"varint,3,opt,name=reused_blocks,json=reusedBlocks,proto3" json:"reused_blocks,omitempty"`    // 前缀命中 block 数(对齐 src/ 冒烟语义)
	PrefillBlocks uint32                 `protobuf:"varint,4,opt,name=prefill_blocks,json=prefillBlocks,proto3" json:"prefill_blocks,omitempty"` // 本次新算 block 数
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`                                         // P3 固定 "COLOCATED";生产才报 PD_SEPARATED / D_DIRECT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_lake_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lake_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_lake_proto_rawDescGZIP(), []int{31}
}

func (x *GenerateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateResponse) GetOutputTokens() []uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return nil
}

func (x *GenerateResponse) GetReusedBlocks() uint32 {
	if x != nil {
		return x.ReusedBlocks
	}
	return 0
}

func (x *GenerateResponse) GetPrefillBlocks() uint32 {
	if x != nil {
		return x.PrefillBlocks
	}
	return 0
}

func (x *GenerateResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

var File_lake_proto protoreflect.FileDescriptor

const file_lake_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lake.proto\x12\x04lake\x1a\fschema.proto\"_\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12&\n" +
	"\x0fresume_from_seq\x18\x02 \x01(\x04R\rresumeFromSeq\"G\n" +
	"\n" +
	"ViewUpdate\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12'\n" +
	"\x06events\x18\x02 \x03(\v2\x0f.lake.ViewEventR\x06events\"\x87\x02\n" +
	"\tViewEvent\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.lake.ViewEvent.KindR\x04kind\x12\x1f\n" +
	"\x02id\x18\x02 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12,\n" +
	"\tlocations\x18\x03 \x03(\v2\x0e.lake.LocationR\tlocations\x12\x1d\n" +
	"\n" +
	"l3_present\x18\x04 \x01(\bR\tl3Present\x12.\n" +
	"\n" +
	"block_kind\x18\x05 \x01(\x0e2\x0f.lake.BlockKindR\tblockKind\"2\n" +
	"\x04Kind\x12\x0e\n" +
	"\n" +
	"REGISTERED\x10\x00\x12\x0f\n" +
	"\vINVALIDATED\x10\x01\x12\t\n" +
	"\x05MOVED\x10\x02\"\x81\x01\n" +
	"\x13LookupPrefixRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12#\n" +
	"\rprefix_hashes\x18\x02 \x03(\fR\fprefixHashes\x12*\n" +
	"\x11requester_node_id\x18\x03 \x01(\tR\x0frequesterNodeId\"\x86\x01\n" +
	"\x14LookupPrefixResponse\x12+\n" +
	"\x06blocks\x18\x01 \x03(\v2\x13.lake.ReusableBlockR\x06blocks\x12\x1d\n" +
	"\n" +
	"hit_length\x18\x02 \x01(\rR\thitLength\x12\"\n" +
	"\rall_local_hit\x18\x03 \x01(\bR\vallLocalHit\"r\n" +
	"\rReusableBlock\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12#\n" +
	"\x04meta\x18\x02 \x01(\v2\x0f.lake.BlockMetaR\x04meta\x12\x1b\n" +
	"\tlocal_hit\x18\x03 \x01(\bR\blocalHit\"2\n" +
	"\rLocateRequest\x12!\n" +
	"\x03ids\x18\x01 \x03(\v2\x0f.lake.KVBlockIDR\x03ids\"9\n" +
	"\x0eLocateResponse\x12'\n" +
	"\x06blocks\x18\x01 \x03(\v2\x0f.lake.BlockMetaR\x06blocks\"~\n" +
	"\x15RegisterBlocksRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x06blocks\x18\x02 \x03(\v2\x0f.lake.BlockMetaR\x06blocks\x12#\n" +
	"\rprefix_hashes\x18\x03 \x03(\fR\fprefixHashes\"}\n" +
	"\bRefDelta\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12!\n" +
	"\x04kind\x18\x02 \x01(\x0e2\r.lake.RefKindR\x04kind\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x05R\x05delta\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"O\n" +
	"\x15RequestBarrierRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xbf\x01\n" +
	"\x0eLeaseHeartbeat\x12'\n" +
	"\x02op\x18\x01 \x01(\x0e2\x17.lake.LeaseHeartbeat.OpR\x02op\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\x04R\tsegmentId\x12\x1f\n" +
	"\vsegment_len\x18\x04 \x01(\x04R\n" +
	"segmentLen\"+\n" +
	"\x02Op\x12\t\n" +
	"\x05MOUNT\x10\x00\x12\v\n" +
	"\aUNMOUNT\x10\x01\x12\r\n" +
	"\tKEEPALIVE\x10\x02\";\n" +
	"\bLeaseAck\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x04R\x05ttlMs\"\xf1\x01\n" +
	"\x0fDispatchRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x122\n" +
	"\freuse_blocks\x18\x03 \x03(\v2\x0f.lake.KVBlockIDR\vreuseBlocks\x126\n" +
	"\x05hints\x18\x04 \x03(\v2 .lake.DispatchRequest.HintsEntryR\x05hints\x1a8\n" +
	"\n" +
	"HintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\n" +
	"LoadReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tqueue_len\x18\x02 \x01(\rR\bqueueLen\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\rR\binFlight\x12#\n" +
	"\rremaining_cap\x18\x04 \x01(\rR\fremainingCap\"]\n" +
	"\x12PlaceBlocksRequest\x12!\n" +
	"\x03ids\x18\x01 \x03(\v2\x0f.lake.KVBlockIDR\x03ids\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\"A\n" +
	"\x14TransferBatchRequest\x12)\n" +
	"\x04reqs\x18\x01 \x03(\v2\x15.lake.TransferRequestR\x04reqs\"\xa2\x01\n" +
	"\x0fTransferRequest\x12&\n" +
	"\x06source\x18\x01 \x01(\v2\x0e.lake.LocationR\x06source\x12*\n" +
	"\x11target_segment_id\x18\x02 \x01(\x04R\x0ftargetSegmentId\x12#\n" +
	"\rtarget_offset\x18\x03 \x01(\x04R\ftargetOffset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\"-\n" +
	"\x10TransferBatchAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\"K\n" +
	"\x15TransferStatusRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\"\xac\x01\n" +
	"\x16TransferStatusResponse\x128\n" +
	"\x05state\x18\x01 \x01(\x0e2\".lake.TransferStatusResponse.StateR\x05state\x12\x1d\n" +
	"\n" +
	"bytes_done\x18\x02 \x01(\x04R\tbytesDone\"9\n" +
	"\x05State\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tIN_FLIGHT\x10\x01\x12\b\n" +
	"\x04DONE\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\"\xa3\x01\n" +
	"\vPullRequest\x12!\n" +
	"\x03ids\x18\x01 \x03(\v2\x0f.lake.KVBlockIDR\x03ids\x12(\n" +
	"\x06policy\x18\x02 \x01(\x0e2\x10.lake.PullPolicyR\x06policy\x12\x1b\n" +
	"\tbudget_ms\x18\x03 \x01(\rR\bbudgetMs\x12*\n" +
	"\x11requester_node_id\x18\x04 \x01(\tR\x0frequesterNodeId\"i\n" +
	"\fPullResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\x04R\x06handle\x12#\n" +
	"\rpulled_length\x18\x02 \x01(\rR\fpulledLength\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"L\n" +
	"\x0ePublishRequest\x12(\n" +
	"\x06slices\x18\x01 \x03(\v2\x10.lake.LayerSliceR\x06slices\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\"z\n" +
	"\n" +
	"LayerSlice\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12\x1b\n" +
	"\tlayer_idx\x18\x02 \x01(\rR\blayerIdx\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\"'\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"V\n" +
	"\x10PutBlocksRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x06blocks\x18\x02 \x03(\v2\x11.lake.OpaqueBlockR\x06blocks\"B\n" +
	"\vOpaqueBlock\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"5\n" +
	"\x10GetBlocksRequest\x12!\n" +
	"\x03ids\x18\x01 \x03(\v2\x0f.lake.KVBlockIDR\x03ids\">\n" +
	"\x11GetBlocksResponse\x12)\n" +
	"\x06blocks\x18\x01 \x03(\v2\x11.lake.OpaqueBlockR\x06blocks\"\xc2\x01\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rprompt_tokens\x18\x03 \x03(\rR\fpromptTokens\x12$\n" +
	"\x0emax_new_tokens\x18\x04 \x01(\rR\fmaxNewTokens\x12*\n" +
	"\x11requester_node_id\x18\x05 \x01(\tR\x0frequesterNodeId\"\xb6\x01\n" +
	"\x10GenerateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\routput_tokens\x18\x02 \x03(\rR\foutputTokens\x12#\n" +
	"\rreused_blocks\x18\x03 \x01(\rR\freusedBlocks\x12%\n" +
	"\x0eprefill_blocks\x18\x04 \x01(\rR\rprefillBlocks\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode*N\n" +
	"\aRefKind\x12\x18\n" +
	"\x14REF_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aREQUEST\x10\x01\x12\r\n" +
	"\tIN_FLIGHT\x10\x02\x12\r\n" +
	"\tWRITEBACK\x10\x03*L\n" +
	"\n" +
	"PullPolicy\x12\x14\n" +
	"\x10PULL_BEST_EFFORT\x10\x00\x12\x16\n" +
	"\x12PULL_WAIT_COMPLETE\x10\x01\x12\x10\n" +
	"\fPULL_TIMEOUT\x10\x022\x9f\x03\n" +
	"\x13ControlPlaneService\x12;\n" +
	"\rSubscribeView\x12\x16.lake.SubscribeRequest\x1a\x10.lake.ViewUpdate0\x01\x12E\n" +
	"\fLookupPrefix\x12\x19.lake.LookupPrefixRequest\x1a\x1a.lake.LookupPrefixResponse\x123\n" +
	"\x06Locate\x12\x13.lake.LocateRequest\x1a\x14.lake.LocateResponse\x128\n" +
	"\x0eRegisterBlocks\x12\x1b.lake.RegisterBlocksRequest\x1a\t.lake.Ack\x12(\n" +
	"\tReportRef\x12\x0e.lake.RefDelta\x1a\t.lake.Ack(\x01\x128\n" +
	"\x0eRequestBarrier\x12\x1b.lake.RequestBarrierRequest\x1a\t.lake.Ack\x121\n" +
	"\x05Lease\x12\x14.lake.LeaseHeartbeat\x1a\x0e.lake.LeaseAck(\x010\x012\x9f\x01\n" +
	"\fAgentService\x12,\n" +
	"\bDispatch\x12\x15.lake.DispatchRequest\x1a\t.lake.Ack\x12-\n" +
	"\n" +
	"ReportLoad\x12\x10.lake.LoadReport\x1a\t.lake.Ack(\x010\x01\x122\n" +
	"\vPlaceBlocks\x12\x18.lake.PlaceBlocksRequest\x1a\t.lake.Ack2\x82\x02\n" +
	"\x0fTransferService\x12D\n" +
	"\x0eSubmitTransfer\x12\x1a.lake.TransferBatchRequest\x1a\x16.lake.TransferBatchAck\x12N\n" +
	"\x11GetTransferStatus\x12\x1b.lake.TransferStatusRequest\x1a\x1c.lake.TransferStatusResponse\x12-\n" +
	"\x04Pull\x12\x11.lake.PullRequest\x1a\x12.lake.PullResponse\x12*\n" +
	"\aPublish\x12\x14.lake.PublishRequest\x1a\t.lake.Ack2\x81\x01\n" +
	"\x11SkeletonKvService\x12.\n" +
	"\tPutBlocks\x12\x16.lake.PutBlocksRequest\x1a\t.lake.Ack\x12<\n" +
	"\tGetBlocks\x12\x16.lake.GetBlocksRequest\x1a\x17.lake.GetBlocksResponse2J\n" +
	"\rWorkerService\x129\n" +
	"\bGenerate\x12\x15.lake.GenerateRequest\x1a\x16.lake.GenerateResponseB)Z'github.com/chengda-wu/lake/go/pb;lakepbb\x06proto3"

var (
	file_lake_proto_rawDescOnce sync.Once
	file_lake_proto_rawDescData []byte
)

func file_lake_proto_rawDescGZIP() []byte {
	file_lake_proto_rawDescOnce.Do(func() {
		file_lake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lake_proto_rawDesc), len(file_lake_proto_rawDesc)))
	})
	return file_lake_proto_rawDescData
}

var file_lake_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_lake_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_lake_proto_goTypes = []any{
	(RefKind)(0),                      // 0: lake.RefKind
	(PullPolicy)(0),                   // 1: lake.PullPolicy
	(ViewEvent_Kind)(0),               // 2: lake.ViewEvent.Kind
	(LeaseHeartbeat_Op)(0),            // 3: lake.LeaseHeartbeat.Op
	(TransferStatusResponse_State)(0), // 4: lake.TransferStatusResponse.State
	(*SubscribeRequest)(nil),          // 5: lake.SubscribeRequest
	(*ViewUpdate)(nil),                // 6: lake.ViewUpdate
	(*ViewEvent)(nil),                 // 7: lake.ViewEvent
	(*LookupPrefixRequest)(nil),       // 8: lake.LookupPrefixRequest
	(*LookupPrefixResponse)(nil),      // 9: lake.LookupPrefixResponse
	(*ReusableBlock)(nil),             // 10: lake.ReusableBlock
	(*LocateRequest)(nil),             // 11: lake.LocateRequest
	(*LocateResponse)(nil),            // 12: lake.LocateResponse
	(*RegisterBlocksRequest)(nil),     // 13: lake.RegisterBlocksRequest
	(*RefDelta)(nil),                  // 14: lake.RefDelta
	(*RequestBarrierRequest)(nil),     // 15: lake.RequestBarrierRequest
	(*LeaseHeartbeat)(nil),            // 16: lake.LeaseHeartbeat
	(*LeaseAck)(nil),                  // 17: lake.LeaseAck
	(*DispatchRequest)(nil),           // 18: lake.DispatchRequest
	(*LoadReport)(nil),                // 19: lake.LoadReport
	(*PlaceBlocksRequest)(nil),        // 20: lake.PlaceBlocksRequest
	(*TransferBatchRequest)(nil),      // 21: lake.TransferBatchRequest
	(*TransferRequest)(nil),           // 22: lake.TransferRequest
	(*TransferBatchAck)(nil),          // 23: lake.TransferBatchAck
	(*TransferStatusRequest)(nil),     // 24: lake.TransferStatusRequest
	(*TransferStatusResponse)(nil),    // 25: lake.TransferStatusResponse
	(*PullRequest)(nil),               // 26: lake.PullRequest
	(*PullResponse)(nil),              // 27: lake.PullResponse
	(*PublishRequest)(nil),            // 28: lake.PublishRequest
	(*LayerSlice)(nil),                // 29: lake.LayerSlice
	(*Ack)(nil),                       // 30: lake.Ack
	(*PutBlocksRequest)(nil),          // 31: lake.PutBlocksRequest
	(*OpaqueBlock)(nil),               // 32: lake.OpaqueBlock
	(*GetBlocksRequest)(nil),          // 33: lake.GetBlocksRequest
	(*GetBlocksResponse)(nil),         // 34: lake.GetBlocksResponse
	(*GenerateRequest)(nil),           // 35: lake.GenerateRequest
	(*GenerateResponse)(nil),          // 36: lake.GenerateResponse
	nil,                               // 37: lake.DispatchRequest.HintsEntry
	(*KVBlockID)(nil),                 // 38: lake.KVBlockID
	(*Location)(nil),                  // 39: lake.Location
	(BlockKind)(0),                    // 40: lake.BlockKind
	(*BlockMeta)(nil),                 // 41: lake.BlockMeta
}
var file_lake_proto_depIdxs = []int32{
	7,  // 0: lake.ViewUpdate.events:type_name -> lake.ViewEvent
	2,  // 1: lake.ViewEvent.kind:type_name -> lake.ViewEvent.Kind
	38, // 2: lake.ViewEvent.id:type_name -> lake.KVBlockID
	39, // 3: lake.ViewEvent.locations:type_name -> lake.Location
	40, // 4: lake.ViewEvent.block_kind:type_name -> lake.BlockKind
	10, // 5: lake.LookupPrefixResponse.blocks:type_name -> lake.ReusableBlock
	38, // 6: lake.ReusableBlock.id:type_name -> lake.KVBlockID
	41, // 7: lake.ReusableBlock.meta:type_name -> lake.BlockMeta
	38, // 8: lake.LocateRequest.ids:type_name -> lake.KVBlockID
	41, // 9: lake.LocateResponse.blocks:type_name -> lake.BlockMeta
	41, // 10: lake.RegisterBlocksRequest.blocks:type_name -> lake.BlockMeta
	38, // 11: lake.RefDelta.id:type_name -> lake.KVBlockID
	0,  // 12: lake.RefDelta.kind:type_name -> lake.RefKind
	3,  // 13: lake.LeaseHeartbeat.op:type_name -> lake.LeaseHeartbeat.Op
	38, // 14: lake.DispatchRequest.reuse_blocks:type_name -> lake.KVBlockID
	37, // 15: lake.DispatchRequest.hints:type_name -> lake.DispatchRequest.HintsEntry
	38, // 16: lake.PlaceBlocksRequest.ids:type_name -> lake.KVBlockID
	22, // 17: lake.TransferBatchRequest.reqs:type_name -> lake.TransferRequest
	39, // 18: lake.TransferRequest.source:type_name -> lake.Location
	4,  // 19: lake.TransferStatusResponse.state:type_name -> lake.TransferStatusResponse.State
	38, // 20: lake.PullRequest.ids:type_name -> lake.KVBlockID
	1,  // 21: lake.PullRequest.policy:type_name -> lake.PullPolicy
	29, // 22: lake.PublishRequest.slices:type_name -> lake.LayerSlice
	38, // 23: lake.LayerSlice.id:type_name -> lake.KVBlockID
	32, // 24: lake.PutBlocksRequest.blocks:type_name -> lake.OpaqueBlock
	38, // 25: lake.OpaqueBlock.id:type_name -> lake.KVBlockID
	38, // 26: lake.GetBlocksRequest.ids:type_name -> lake.KVBlockID
	32, // 27: lake.GetBlocksResponse.blocks:type_name -> lake.OpaqueBlock
	5,  // 28: lake.ControlPlaneService.SubscribeView:input_type -> lake.SubscribeRequest
	8,  // 29: lake.ControlPlaneService.LookupPrefix:input_type -> lake.LookupPrefixRequest
	11, // 30: lake.ControlPlaneService.Locate:input_type -> lake.LocateRequest
	13, // 31: lake.ControlPlaneService.RegisterBlocks:input_type -> lake.RegisterBlocksRequest
	14, // 32: lake.ControlPlaneService.ReportRef:input_type -> lake.RefDelta
	15, // 33: lake.ControlPlaneService.RequestBarrier:input_type -> lake.RequestBarrierRequest
	16, // 34: lake.ControlPlaneService.Lease:input_type -> lake.LeaseHeartbeat
	18, // 35: lake.AgentService.Dispatch:input_type -> lake.DispatchRequest
	19, // 36: lake.AgentService.ReportLoad:input_type -> lake.LoadReport
	20, // 37: lake.AgentService.PlaceBlocks:input_type -> lake.PlaceBlocksRequest
	21, // 38: lake.TransferService.SubmitTransfer:input_type -> lake.TransferBatchRequest
	24, // 39: lake.TransferService.GetTransferStatus:input_type -> lake.TransferStatusRequest
	26, // 40: lake.TransferService.Pull:input_type -> lake.PullRequest
	28, // 41: lake.TransferService.Publish:input_type -> lake.PublishRequest
	31, // 42: lake.SkeletonKvService.PutBlocks:input_type -> lake.PutBlocksRequest
	33, // 43: lake.SkeletonKvService.GetBlocks:input_type -> lake.GetBlocksRequest
	35, // 44: lake.WorkerService.Generate:input_type -> lake.GenerateRequest
	6,  // 45: lake.ControlPlaneService.SubscribeView:output_type -> lake.ViewUpdate
	9,  // 46: lake.ControlPlaneService.LookupPrefix:output_type -> lake.LookupPrefixResponse
	12, // 47: lake.ControlPlaneService.Locate:output_type -> lake.LocateResponse
	30, // 48: lake.ControlPlaneService.RegisterBlocks:output_type -> lake.Ack
	30, // 49: lake.ControlPlaneService.ReportRef:output_type -> lake.Ack
	30, // 50: lake.ControlPlaneService.RequestBarrier:output_type -> lake.Ack
	17, // 51: lake.ControlPlaneService.Lease:output_type -> lake.LeaseAck
	30, // 52: lake.AgentService.Dispatch:output_type -> lake.Ack
	30, // 53: lake.AgentService.ReportLoad:output_type -> lake.Ack
	30, // 54: lake.AgentService.PlaceBlocks:output_type -> lake.Ack
	23, // 55: lake.TransferService.SubmitTransfer:output_type -> lake.TransferBatchAck
	25, // 56: lake.TransferService.GetTransferStatus:output_type -> lake.TransferStatusResponse
	27, // 57: lake.TransferService.Pull:output_type -> lake.PullResponse
	30, // 58: lake.TransferService.Publish:output_type -> lake.Ack
	30, // 59: lake.SkeletonKvService.PutBlocks:output_type -> lake.Ack
	34, // 60: lake.SkeletonKvService.GetBlocks:output_type -> lake.GetBlocksResponse
	36, // 61: lake.WorkerService.Generate:output_type -> lake.GenerateResponse
	45, // [45:62] is the sub-list for method output_type
	28, // [28:45] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_lake_proto_init() }
func file_lake_proto_init() {
	if File_lake_proto != nil {
		return
	}
	file_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lake_proto_rawDesc), len(file_lake_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_lake_proto_goTypes,
		DependencyIndexes: file_lake_proto_depIdxs,
		EnumInfos:         file_lake_proto_enumTypes,
		MessageInfos:      file_lake_proto_msgTypes,
	}.Build()
	File_lake_proto = out.File
	file_lake_proto_goTypes = nil
	file_lake_proto_depIdxs = nil
}
