// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: lake.proto

package lakepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_SubscribeView_FullMethodName  = "/lake.ControlPlaneService/SubscribeView"
	ControlPlaneService_LookupPrefix_FullMethodName   = "/lake.ControlPlaneService/LookupPrefix"
	ControlPlaneService_Locate_FullMethodName         = "/lake.ControlPlaneService/Locate"
	ControlPlaneService_RegisterBlocks_FullMethodName = "/lake.ControlPlaneService/RegisterBlocks"
	ControlPlaneService_RequestBarrier_FullMethodName = "/lake.ControlPlaneService/RequestBarrier"
	ControlPlaneService_Lease_FullMethodName          = "/lake.ControlPlaneService/Lease"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
// =============================================================================
type ControlPlaneServiceClient interface {
	// 边3/4:订阅位置视图 live 镜像(Router 与 agent 同协议、不同订阅者,#3 已定)。
	//
	//	事件形态参考 vLLM BlockStored/BlockRemoved、Mooncake Conductor 订阅事件。
	//	单权威 → 单流 sequence + gap replay(见 control-plane.md「粒度与协议」)。
	SubscribeView(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ViewUpdate], error)
	// Router 选路查询:输入 (model_id, 前缀 block hashes),输出可复用 block 列表 + 位置 + 本地命中。
	//
	//	**非热路径常态**——热路径 Router 在本地位置视图镜像上 match(零 RPC,见 B3)。
	//	本 RPC 是**权威回退**:冷启动 / 镜像 gap / 调试时查控制面权威树(与 Locate 同档,线性一致)。
	//	仿 SGLang match_prefix 的集群版。
	LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*LookupPrefixResponse, error)
	// agent 搬 KV:同步查权威树(线性一致)。常态走镜像/本地 slot 不查,仅镜像不可信时查
	//
	//	(见 kv-cache-pool.md「搬 KV 查权威分层」)。
	Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	// 满块注册:**耐久性由 agent 本地完成**(写 L2 durable)后,只调一次本 RPC = PutEnd。
	//
	//	PutStart 不进控制面(agent 本地记账即可),防半块被读。仿 Mooncake PutEnd 的控制面侧。
	//	release 一致,写控制面内存,不进 etcd。
	//	与 Publish 的区别:Publish(可多次、逐层 slice)只更新位置视图;RegisterBlocks(满块 + L2 durable)才进 radix + 置 l3_present/L2。
	RegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
	// 请求结束屏障:release → flush L2 + ack → 控制面更新目录(见 consistency.md §3)。
	RequestBarrier(ctx context.Context, in *RequestBarrierRequest, opts ...grpc.CallOption) (*Ack, error)
	// lease:节点 mount/unmount segment + 续命(仿 Mooncake MountSegment/UnmountSegment + client_live_ttl_sec)。
	Lease(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck], error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) SubscribeView(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ViewUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_SubscribeView_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ViewUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeViewClient = grpc.ServerStreamingClient[ViewUpdate]

func (c *controlPlaneServiceClient) LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*LookupPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupPrefixResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_LookupPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocateResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_Locate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RequestBarrier(ctx context.Context, in *RequestBarrierRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RequestBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) Lease(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[1], ControlPlaneService_Lease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeaseHeartbeat, LeaseAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_LeaseClient = grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck]

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// =============================================================================
// ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
// =============================================================================
type ControlPlaneServiceServer interface {
	// 边3/4:订阅位置视图 live 镜像(Router 与 agent 同协议、不同订阅者,#3 已定)。
	//
	//	事件形态参考 vLLM BlockStored/BlockRemoved、Mooncake Conductor 订阅事件。
	//	单权威 → 单流 sequence + gap replay(见 control-plane.md「粒度与协议」)。
	SubscribeView(*SubscribeRequest, grpc.ServerStreamingServer[ViewUpdate]) error
	// Router 选路查询:输入 (model_id, 前缀 block hashes),输出可复用 block 列表 + 位置 + 本地命中。
	//
	//	**非热路径常态**——热路径 Router 在本地位置视图镜像上 match(零 RPC,见 B3)。
	//	本 RPC 是**权威回退**:冷启动 / 镜像 gap / 调试时查控制面权威树(与 Locate 同档,线性一致)。
	//	仿 SGLang match_prefix 的集群版。
	LookupPrefix(context.Context, *LookupPrefixRequest) (*LookupPrefixResponse, error)
	// agent 搬 KV:同步查权威树(线性一致)。常态走镜像/本地 slot 不查,仅镜像不可信时查
	//
	//	(见 kv-cache-pool.md「搬 KV 查权威分层」)。
	Locate(context.Context, *LocateRequest) (*LocateResponse, error)
	// 满块注册:**耐久性由 agent 本地完成**(写 L2 durable)后,只调一次本 RPC = PutEnd。
	//
	//	PutStart 不进控制面(agent 本地记账即可),防半块被读。仿 Mooncake PutEnd 的控制面侧。
	//	release 一致,写控制面内存,不进 etcd。
	//	与 Publish 的区别:Publish(可多次、逐层 slice)只更新位置视图;RegisterBlocks(满块 + L2 durable)才进 radix + 置 l3_present/L2。
	RegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error)
	// 请求结束屏障:release → flush L2 + ack → 控制面更新目录(见 consistency.md §3)。
	RequestBarrier(context.Context, *RequestBarrierRequest) (*Ack, error)
	// lease:节点 mount/unmount segment + 续命(仿 Mooncake MountSegment/UnmountSegment + client_live_ttl_sec)。
	Lease(grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]) error
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) SubscribeView(*SubscribeRequest, grpc.ServerStreamingServer[ViewUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeView not implemented")
}
func (UnimplementedControlPlaneServiceServer) LookupPrefix(context.Context, *LookupPrefixRequest) (*LookupPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupPrefix not implemented")
}
func (UnimplementedControlPlaneServiceServer) Locate(context.Context, *LocateRequest) (*LocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Locate not implemented")
}
func (UnimplementedControlPlaneServiceServer) RegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBlocks not implemented")
}
func (UnimplementedControlPlaneServiceServer) RequestBarrier(context.Context, *RequestBarrierRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBarrier not implemented")
}
func (UnimplementedControlPlaneServiceServer) Lease(grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]) error {
	return status.Error(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_SubscribeView_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).SubscribeView(m, &grpc.GenericServerStream[SubscribeRequest, ViewUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeViewServer = grpc.ServerStreamingServer[ViewUpdate]

func _ControlPlaneService_LookupPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).LookupPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_LookupPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).LookupPrefix(ctx, req.(*LookupPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_Locate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).Locate(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RegisterBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterBlocks(ctx, req.(*RegisterBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RequestBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RequestBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RequestBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RequestBarrier(ctx, req.(*RequestBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_Lease_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServiceServer).Lease(&grpc.GenericServerStream[LeaseHeartbeat, LeaseAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_LeaseServer = grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupPrefix",
			Handler:    _ControlPlaneService_LookupPrefix_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _ControlPlaneService_Locate_Handler,
		},
		{
			MethodName: "RegisterBlocks",
			Handler:    _ControlPlaneService_RegisterBlocks_Handler,
		},
		{
			MethodName: "RequestBarrier",
			Handler:    _ControlPlaneService_RequestBarrier_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeView",
			Handler:       _ControlPlaneService_SubscribeView_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Lease",
			Handler:       _ControlPlaneService_Lease_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lake.proto",
}

const (
	AgentService_Dispatch_FullMethodName    = "/lake.AgentService/Dispatch"
	AgentService_ReportLoad_FullMethodName  = "/lake.AgentService/ReportLoad"
	AgentService_PlaceBlocks_FullMethodName = "/lake.AgentService/PlaceBlocks"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// AgentService — 边10:Router/控制面 → agent
// =============================================================================
type AgentServiceClient interface {
	// 边10:Router 选好模式+节点后,下发调度指令给目标 agent(组 batch)。
	//
	//	携带 hints(agent_hints/kv_hints),与 #13 Bifrost 透传对齐(仿 SGLang #21846 agent_hints)。
	//	本稿只定调度骨架;request_id / 输入 token / 采样参数等请求体字段后续 PR 补。
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Ack, error)
	// 边10:agent 上报负载(队列长度/in-flight/剩余容量),供过载信号 P7 对接 Bifrost。
	//
	//	流式上报、流式 ack(避免客户端关流才 ack 的运维别扭)。
	ReportLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoadReport, Ack], error)
	// 控制面 → agent:补拉放置(缺失 KV 放到指定节点 HBM,方案 Z 单向耦合)。
	PlaceBlocks(ctx context.Context, in *PlaceBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoadReport, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportLoad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadReport, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportLoadClient = grpc.BidiStreamingClient[LoadReport, Ack]

func (c *agentServiceClient) PlaceBlocks(ctx context.Context, in *PlaceBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_PlaceBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// =============================================================================
// AgentService — 边10:Router/控制面 → agent
// =============================================================================
type AgentServiceServer interface {
	// 边10:Router 选好模式+节点后,下发调度指令给目标 agent(组 batch)。
	//
	//	携带 hints(agent_hints/kv_hints),与 #13 Bifrost 透传对齐(仿 SGLang #21846 agent_hints)。
	//	本稿只定调度骨架;request_id / 输入 token / 采样参数等请求体字段后续 PR 补。
	Dispatch(context.Context, *DispatchRequest) (*Ack, error)
	// 边10:agent 上报负载(队列长度/in-flight/剩余容量),供过载信号 P7 对接 Bifrost。
	//
	//	流式上报、流式 ack(避免客户端关流才 ack 的运维别扭)。
	ReportLoad(grpc.BidiStreamingServer[LoadReport, Ack]) error
	// 控制面 → agent:补拉放置(缺失 KV 放到指定节点 HBM,方案 Z 单向耦合)。
	PlaceBlocks(context.Context, *PlaceBlocksRequest) (*Ack, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Dispatch(context.Context, *DispatchRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedAgentServiceServer) ReportLoad(grpc.BidiStreamingServer[LoadReport, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedAgentServiceServer) PlaceBlocks(context.Context, *PlaceBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBlocks not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportLoad(&grpc.GenericServerStream[LoadReport, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportLoadServer = grpc.BidiStreamingServer[LoadReport, Ack]

func _AgentService_PlaceBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PlaceBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PlaceBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PlaceBlocks(ctx, req.(*PlaceBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _AgentService_Dispatch_Handler,
		},
		{
			MethodName: "PlaceBlocks",
			Handler:    _AgentService_PlaceBlocks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportLoad",
			Handler:       _AgentService_ReportLoad_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lake.proto",
}

const (
	TransferService_SubmitTransfer_FullMethodName    = "/lake.TransferService/SubmitTransfer"
	TransferService_GetTransferStatus_FullMethodName = "/lake.TransferService/GetTransferStatus"
	TransferService_Pull_FullMethodName              = "/lake.TransferService/Pull"
	TransferService_Publish_FullMethodName           = "/lake.TransferService/Publish"
)

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// TransferService — 边7/8:RDMA 传输的控制信令(字节走 RDMA 旁路)
// =============================================================================
type TransferServiceClient interface {
	// 仿 Mooncake:allocateBatchID → submitTransfer(batch,{TransferRequest}) → getTransferStatus。
	SubmitTransfer(ctx context.Context, in *TransferBatchRequest, opts ...grpc.CallOption) (*TransferBatchAck, error)
	GetTransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	// 引擎契约:pull(block_ids) 返回 handle,publish(逐层增量)上报产出。
	//
	//	跨实例控制信令;worker 本机调 agent 走 FFI(边6)不进 proto。
	//	Pull 异步 + 可中断(仿 SGLang prefetch 三策略 + 预算);Publish layer-wise(仿 SGLang on_publish + page_first_direct)。
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) SubmitTransfer(ctx context.Context, in *TransferBatchRequest, opts ...grpc.CallOption) (*TransferBatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBatchAck)
	err := c.cc.Invoke(ctx, TransferService_SubmitTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetTransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, TransferService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, TransferService_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TransferService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility.
//
// =============================================================================
// TransferService — 边7/8:RDMA 传输的控制信令(字节走 RDMA 旁路)
// =============================================================================
type TransferServiceServer interface {
	// 仿 Mooncake:allocateBatchID → submitTransfer(batch,{TransferRequest}) → getTransferStatus。
	SubmitTransfer(context.Context, *TransferBatchRequest) (*TransferBatchAck, error)
	GetTransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error)
	// 引擎契约:pull(block_ids) 返回 handle,publish(逐层增量)上报产出。
	//
	//	跨实例控制信令;worker 本机调 agent 走 FFI(边6)不进 proto。
	//	Pull 异步 + 可中断(仿 SGLang prefetch 三策略 + 预算);Publish layer-wise(仿 SGLang on_publish + page_first_direct)。
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	Publish(context.Context, *PublishRequest) (*Ack, error)
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferServiceServer struct{}

func (UnimplementedTransferServiceServer) SubmitTransfer(context.Context, *TransferBatchRequest) (*TransferBatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransfer not implemented")
}
func (UnimplementedTransferServiceServer) GetTransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedTransferServiceServer) Pull(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedTransferServiceServer) Publish(context.Context, *PublishRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}
func (UnimplementedTransferServiceServer) testEmbeddedByValue()                         {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	// If the following call panics, it indicates UnimplementedTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_SubmitTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).SubmitTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_SubmitTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).SubmitTransfer(ctx, req.(*TransferBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, req.(*TransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransfer",
			Handler:    _TransferService_SubmitTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _TransferService_GetTransferStatus_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _TransferService_Pull_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _TransferService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lake.proto",
}
