// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: lake.proto

package lakepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_SubscribeView_FullMethodName       = "/lake.ControlPlaneService/SubscribeView"
	ControlPlaneService_LookupPrefix_FullMethodName        = "/lake.ControlPlaneService/LookupPrefix"
	ControlPlaneService_Locate_FullMethodName              = "/lake.ControlPlaneService/Locate"
	ControlPlaneService_AdmitRegisterBlocks_FullMethodName = "/lake.ControlPlaneService/AdmitRegisterBlocks"
	ControlPlaneService_RegisterBlocks_FullMethodName      = "/lake.ControlPlaneService/RegisterBlocks"
	ControlPlaneService_ReportRef_FullMethodName           = "/lake.ControlPlaneService/ReportRef"
	ControlPlaneService_RequestBarrier_FullMethodName      = "/lake.ControlPlaneService/RequestBarrier"
	ControlPlaneService_Lease_FullMethodName               = "/lake.ControlPlaneService/Lease"
	ControlPlaneService_RegisterModel_FullMethodName       = "/lake.ControlPlaneService/RegisterModel"
	ControlPlaneService_DeregisterModel_FullMethodName     = "/lake.ControlPlaneService/DeregisterModel"
	ControlPlaneService_SetModelQuota_FullMethodName       = "/lake.ControlPlaneService/SetModelQuota"
	ControlPlaneService_GetModelQuota_FullMethodName       = "/lake.ControlPlaneService/GetModelQuota"
	ControlPlaneService_ReconcileOrphans_FullMethodName    = "/lake.ControlPlaneService/ReconcileOrphans"
	ControlPlaneService_DiscardBlocks_FullMethodName       = "/lake.ControlPlaneService/DiscardBlocks"
	ControlPlaneService_SaveCheckpoint_FullMethodName      = "/lake.ControlPlaneService/SaveCheckpoint"
	ControlPlaneService_RestoreCheckpoint_FullMethodName   = "/lake.ControlPlaneService/RestoreCheckpoint"
	ControlPlaneService_TriggerDefrag_FullMethodName       = "/lake.ControlPlaneService/TriggerDefrag"
	ControlPlaneService_PauseBackground_FullMethodName     = "/lake.ControlPlaneService/PauseBackground"
	ControlPlaneService_GetShardMap_FullMethodName         = "/lake.ControlPlaneService/GetShardMap"
	ControlPlaneService_JoinShardNode_FullMethodName       = "/lake.ControlPlaneService/JoinShardNode"
	ControlPlaneService_DrainShardNode_FullMethodName      = "/lake.ControlPlaneService/DrainShardNode"
	ControlPlaneService_RemoveShardNode_FullMethodName     = "/lake.ControlPlaneService/RemoveShardNode"
	ControlPlaneService_ReportHits_FullMethodName          = "/lake.ControlPlaneService/ReportHits"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
// =============================================================================
type ControlPlaneServiceClient interface {
	// 边3/4:订阅位置视图 live 镜像(Router 与 agent 同协议、不同订阅者,#3 已定)。
	//
	//	事件形态参考 vLLM BlockStored/BlockRemoved、Mooncake Conductor 订阅事件。
	//	单权威 → 单流 sequence + gap replay(见 control-plane.md「粒度与协议」)。
	SubscribeView(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ViewUpdate], error)
	// Router 选路查询:输入 (model_id, 前缀 block hashes),输出可复用 block 列表 + 位置 + 本地命中。
	//
	//	**非热路径常态**——热路径 Router 在本地位置视图镜像上 match(零 RPC,见 B3)。
	//	本 RPC 是**权威回退**:冷启动 / 镜像 gap / 调试时查控制面权威树(与 Locate 同档,线性一致)。
	//	仿 SGLang match_prefix 的集群版。
	LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*LookupPrefixResponse, error)
	// agent 搬 KV:同步查权威树(线性一致)。常态走镜像/本地 slot 不查,仅镜像不可信时查
	//
	//	(见 kv-cache-pool.md「搬 KV 查权威分层」)。
	Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	// P4.6:配额写前准入(方案 A)。纯检查、不 reserve、不改位置视图。
	//
	//	对齐 Mooncake PutStart 的「写前问 Master」公开边界;无 reserved 占座(Reserve* → 多进程/P4.7)。
	//	agent 须在 flush durable **之前**调用;触硬 → Ack.ok=false + backpressure。
	//	请求体复用 RegisterBlocksRequest(只读 model/revision/pool_kind/block hashes 计费;
	//	locations/l3_present 可空)。与进程内 ControlPlanePort::admit_register_blocks 同语义。
	AdmitRegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
	// 满块注册:**耐久性由 agent 本地完成**(写 L2 durable)后,只调一次本 RPC = PutEnd。
	//
	//	**可见性** PutStart(半块本地记账、防脏读)仍不进控制面; **配额** 写前走 AdmitRegisterBlocks。
	//	仿 Mooncake PutEnd 的控制面侧。release 一致,写控制面内存,不进 etcd。
	//	与 Publish 的区别:Publish(可多次、逐层 slice)只更新位置视图;RegisterBlocks(满块 + L2 durable)才进 radix + 置 l3_present/L2。
	//	P4.2:须带 prefix_hashes 全链以便控制面建 PositionalLineageHash;`blocks` 可为 miss 后缀。
	//	P4.6:触硬 → ok=false + backpressure;建议先 AdmitRegisterBlocks 再 flush。
	RegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
	// P4.2–P4.3:**控制面合账骨架**（非完整两级 ref）。
	//
	//	累加 delta → global_refs；**忽略 RefKind**（不按 kind 分账）。
	//	P4.3:agent `PutEndSession` 对 WRITEBACK 调本 RPC（+1 注册后 / -1 屏障前）；
	//	本地一级 REQUEST/IN_FLIGHT 与 CP 分 kind → 后续。
	//	流式：先收齐再 **全有或全无** apply（任一条未知 block → 整批不改，可安全重试）。
	//	不进 ViewEvent(B1)。
	ReportRef(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RefDelta, Ack], error)
	// 请求结束屏障(consistency.md §3):agent 已 flush L2 + ReportRef(WRITEBACK,-1) 后调用；
	//
	//	CP 记录完成（目录/checkpoint 后续）。
	RequestBarrier(ctx context.Context, in *RequestBarrierRequest, opts ...grpc.CallOption) (*Ack, error)
	// lease:节点 mount/unmount segment + 续命(仿 Mooncake MountSegment/UnmountSegment + client_live_ttl_sec)。
	Lease(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck], error)
	// P4.5:多模型生命周期(F11)。注册登记 (model_id, revision) 命名空间 + 元数据;
	//
	//	下线级联删该命名空间 radix 子树 + 位置视图(字节 GC → P4.7)。
	RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*Ack, error)
	DeregisterModel(ctx context.Context, in *DeregisterModelRequest, opts ...grpc.CallOption) (*Ack, error)
	// P4.6:按模型软/硬配额 + 借用 + 背压(F11)。配额挂 (model_id, revision) 命名空间。
	//
	//	触硬配额 → Ack.backpressure 上报;请求级 shedding 仍归 gateway,池内不拒请求。
	//	写路径:AdmitRegisterBlocks(写前) / RegisterBlocks(写后确认) 均可带 backpressure。
	SetModelQuota(ctx context.Context, in *SetModelQuotaRequest, opts ...grpc.CallOption) (*Ack, error)
	GetModelQuota(ctx context.Context, in *GetModelQuotaRequest, opts ...grpc.CallOption) (*GetModelQuotaResponse, error)
	// P4.7:GC + 崩溃 reconcile(F11)。
	//   - 上报/扫孤儿(对齐 Mooncake put_start_discard_timeout zombie);
	//   - dead_node_id → 节点级 reconcile(清该节点 ref + 摘 L0;兜底 writeback 泄漏);
	//   - gc_cold_limit → 冷块摘 L0/L1(留 L2/L3 durable 后盾);
	//   - 元数据先于字节删:Response 列出待删 id,agent/kv-pool 再删 bytes。
	ReconcileOrphans(ctx context.Context, in *ReconcileOrphansRequest, opts ...grpc.CallOption) (*ReconcileOrphansResponse, error)
	// 显式摘块(元数据);返回 Ack 后调用方删字节。
	DiscardBlocks(ctx context.Context, in *DiscardBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
	// 降频 checkpoint(P4=内存 mock;真 etcd → P6)。Save 写出快照;Restore 重建权威。
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	RestoreCheckpoint(ctx context.Context, in *RestoreCheckpointRequest, opts ...grpc.CallOption) (*Ack, error)
	// P4.8:碎片整理(F11)。逻辑共置 + 物理压实计划;执行走 agent TierPipeline + BandwidthPool。
	//
	//	返回 planned moves;字节搬迁/段压实在存储层,CP 只出计划并在 Moved 后更新 Location。
	TriggerDefrag(ctx context.Context, in *TriggerDefragRequest, opts ...grpc.CallOption) (*TriggerDefragResponse, error)
	// 暂停/恢复共享后台带宽池(promote/demote/GC/defrag,<10%)。
	PauseBackground(ctx context.Context, in *PauseBackgroundRequest, opts ...grpc.CallOption) (*Ack, error)
	// P4.9:一致性哈希分片(F11 扩缩)。单测模拟环/最小迁移/Drain;真跨机字节迁移 → P5。
	GetShardMap(ctx context.Context, in *GetShardMapRequest, opts ...grpc.CallOption) (*GetShardMapResponse, error)
	// 加入 KV Node → 重算环,仅返回落在新节点区间的迁移计划(最小迁移)。
	//
	//	P7 收口(方案 Z):join 后**新节点 warmup 由池侧自主决策发起**(CP 按
	//	hit_count 选热块 → agent PlaceBlocks),Router 只报告命中(ReportHits)、
	//	不指挥放置。
	JoinShardNode(ctx context.Context, in *JoinShardNodeRequest, opts ...grpc.CallOption) (*JoinShardNodeResponse, error)
	// 缩容:标记 Drain + 迁出计划 + 需先推 L2 的 block 列表(逻辑;字节迁移 P5)。
	DrainShardNode(ctx context.Context, in *DrainShardNodeRequest, opts ...grpc.CallOption) (*DrainShardNodeResponse, error)
	// Drain 完成后从环移除(无剩余所有权时)。
	RemoveShardNode(ctx context.Context, in *RemoveShardNodeRequest, opts ...grpc.CallOption) (*Ack, error)
	// P7 收口:命中上报(best-effort 批量)。Router 在本地镜像上观测到前缀命中后
	//
	//	批量回传,CP 累计到 radix 节点 hit_count(SGLang TreeNode.hit_count 同款),
	//	供 promote 准入 / 扩容 warmup 选块 / 未来方案 Z 预放置复用——一套热度信号。
	//	丢失可容忍(计数偏弱),不进 ViewEvent。
	ReportHits(ctx context.Context, in *ReportHitsRequest, opts ...grpc.CallOption) (*Ack, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) SubscribeView(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ViewUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[0], ControlPlaneService_SubscribeView_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ViewUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeViewClient = grpc.ServerStreamingClient[ViewUpdate]

func (c *controlPlaneServiceClient) LookupPrefix(ctx context.Context, in *LookupPrefixRequest, opts ...grpc.CallOption) (*LookupPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupPrefixResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_LookupPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocateResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_Locate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) AdmitRegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_AdmitRegisterBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RegisterBlocks(ctx context.Context, in *RegisterBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportRef(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RefDelta, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[1], ControlPlaneService_ReportRef_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RefDelta, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ReportRefClient = grpc.ClientStreamingClient[RefDelta, Ack]

func (c *controlPlaneServiceClient) RequestBarrier(ctx context.Context, in *RequestBarrierRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RequestBarrier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) Lease(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlPlaneService_ServiceDesc.Streams[2], ControlPlaneService_Lease_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LeaseHeartbeat, LeaseAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_LeaseClient = grpc.BidiStreamingClient[LeaseHeartbeat, LeaseAck]

func (c *controlPlaneServiceClient) RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RegisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) DeregisterModel(ctx context.Context, in *DeregisterModelRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_DeregisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) SetModelQuota(ctx context.Context, in *SetModelQuotaRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_SetModelQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetModelQuota(ctx context.Context, in *GetModelQuotaRequest, opts ...grpc.CallOption) (*GetModelQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelQuotaResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetModelQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReconcileOrphans(ctx context.Context, in *ReconcileOrphansRequest, opts ...grpc.CallOption) (*ReconcileOrphansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileOrphansResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReconcileOrphans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) DiscardBlocks(ctx context.Context, in *DiscardBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_DiscardBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RestoreCheckpoint(ctx context.Context, in *RestoreCheckpointRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RestoreCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) TriggerDefrag(ctx context.Context, in *TriggerDefragRequest, opts ...grpc.CallOption) (*TriggerDefragResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerDefragResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_TriggerDefrag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) PauseBackground(ctx context.Context, in *PauseBackgroundRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_PauseBackground_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetShardMap(ctx context.Context, in *GetShardMapRequest, opts ...grpc.CallOption) (*GetShardMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShardMapResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetShardMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) JoinShardNode(ctx context.Context, in *JoinShardNodeRequest, opts ...grpc.CallOption) (*JoinShardNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinShardNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_JoinShardNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) DrainShardNode(ctx context.Context, in *DrainShardNodeRequest, opts ...grpc.CallOption) (*DrainShardNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainShardNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_DrainShardNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) RemoveShardNode(ctx context.Context, in *RemoveShardNodeRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_RemoveShardNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ReportHits(ctx context.Context, in *ReportHitsRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ControlPlaneService_ReportHits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// =============================================================================
// ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
// =============================================================================
type ControlPlaneServiceServer interface {
	// 边3/4:订阅位置视图 live 镜像(Router 与 agent 同协议、不同订阅者,#3 已定)。
	//
	//	事件形态参考 vLLM BlockStored/BlockRemoved、Mooncake Conductor 订阅事件。
	//	单权威 → 单流 sequence + gap replay(见 control-plane.md「粒度与协议」)。
	SubscribeView(*SubscribeRequest, grpc.ServerStreamingServer[ViewUpdate]) error
	// Router 选路查询:输入 (model_id, 前缀 block hashes),输出可复用 block 列表 + 位置 + 本地命中。
	//
	//	**非热路径常态**——热路径 Router 在本地位置视图镜像上 match(零 RPC,见 B3)。
	//	本 RPC 是**权威回退**:冷启动 / 镜像 gap / 调试时查控制面权威树(与 Locate 同档,线性一致)。
	//	仿 SGLang match_prefix 的集群版。
	LookupPrefix(context.Context, *LookupPrefixRequest) (*LookupPrefixResponse, error)
	// agent 搬 KV:同步查权威树(线性一致)。常态走镜像/本地 slot 不查,仅镜像不可信时查
	//
	//	(见 kv-cache-pool.md「搬 KV 查权威分层」)。
	Locate(context.Context, *LocateRequest) (*LocateResponse, error)
	// P4.6:配额写前准入(方案 A)。纯检查、不 reserve、不改位置视图。
	//
	//	对齐 Mooncake PutStart 的「写前问 Master」公开边界;无 reserved 占座(Reserve* → 多进程/P4.7)。
	//	agent 须在 flush durable **之前**调用;触硬 → Ack.ok=false + backpressure。
	//	请求体复用 RegisterBlocksRequest(只读 model/revision/pool_kind/block hashes 计费;
	//	locations/l3_present 可空)。与进程内 ControlPlanePort::admit_register_blocks 同语义。
	AdmitRegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error)
	// 满块注册:**耐久性由 agent 本地完成**(写 L2 durable)后,只调一次本 RPC = PutEnd。
	//
	//	**可见性** PutStart(半块本地记账、防脏读)仍不进控制面; **配额** 写前走 AdmitRegisterBlocks。
	//	仿 Mooncake PutEnd 的控制面侧。release 一致,写控制面内存,不进 etcd。
	//	与 Publish 的区别:Publish(可多次、逐层 slice)只更新位置视图;RegisterBlocks(满块 + L2 durable)才进 radix + 置 l3_present/L2。
	//	P4.2:须带 prefix_hashes 全链以便控制面建 PositionalLineageHash;`blocks` 可为 miss 后缀。
	//	P4.6:触硬 → ok=false + backpressure;建议先 AdmitRegisterBlocks 再 flush。
	RegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error)
	// P4.2–P4.3:**控制面合账骨架**（非完整两级 ref）。
	//
	//	累加 delta → global_refs；**忽略 RefKind**（不按 kind 分账）。
	//	P4.3:agent `PutEndSession` 对 WRITEBACK 调本 RPC（+1 注册后 / -1 屏障前）；
	//	本地一级 REQUEST/IN_FLIGHT 与 CP 分 kind → 后续。
	//	流式：先收齐再 **全有或全无** apply（任一条未知 block → 整批不改，可安全重试）。
	//	不进 ViewEvent(B1)。
	ReportRef(grpc.ClientStreamingServer[RefDelta, Ack]) error
	// 请求结束屏障(consistency.md §3):agent 已 flush L2 + ReportRef(WRITEBACK,-1) 后调用；
	//
	//	CP 记录完成（目录/checkpoint 后续）。
	RequestBarrier(context.Context, *RequestBarrierRequest) (*Ack, error)
	// lease:节点 mount/unmount segment + 续命(仿 Mooncake MountSegment/UnmountSegment + client_live_ttl_sec)。
	Lease(grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]) error
	// P4.5:多模型生命周期(F11)。注册登记 (model_id, revision) 命名空间 + 元数据;
	//
	//	下线级联删该命名空间 radix 子树 + 位置视图(字节 GC → P4.7)。
	RegisterModel(context.Context, *RegisterModelRequest) (*Ack, error)
	DeregisterModel(context.Context, *DeregisterModelRequest) (*Ack, error)
	// P4.6:按模型软/硬配额 + 借用 + 背压(F11)。配额挂 (model_id, revision) 命名空间。
	//
	//	触硬配额 → Ack.backpressure 上报;请求级 shedding 仍归 gateway,池内不拒请求。
	//	写路径:AdmitRegisterBlocks(写前) / RegisterBlocks(写后确认) 均可带 backpressure。
	SetModelQuota(context.Context, *SetModelQuotaRequest) (*Ack, error)
	GetModelQuota(context.Context, *GetModelQuotaRequest) (*GetModelQuotaResponse, error)
	// P4.7:GC + 崩溃 reconcile(F11)。
	//   - 上报/扫孤儿(对齐 Mooncake put_start_discard_timeout zombie);
	//   - dead_node_id → 节点级 reconcile(清该节点 ref + 摘 L0;兜底 writeback 泄漏);
	//   - gc_cold_limit → 冷块摘 L0/L1(留 L2/L3 durable 后盾);
	//   - 元数据先于字节删:Response 列出待删 id,agent/kv-pool 再删 bytes。
	ReconcileOrphans(context.Context, *ReconcileOrphansRequest) (*ReconcileOrphansResponse, error)
	// 显式摘块(元数据);返回 Ack 后调用方删字节。
	DiscardBlocks(context.Context, *DiscardBlocksRequest) (*Ack, error)
	// 降频 checkpoint(P4=内存 mock;真 etcd → P6)。Save 写出快照;Restore 重建权威。
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	RestoreCheckpoint(context.Context, *RestoreCheckpointRequest) (*Ack, error)
	// P4.8:碎片整理(F11)。逻辑共置 + 物理压实计划;执行走 agent TierPipeline + BandwidthPool。
	//
	//	返回 planned moves;字节搬迁/段压实在存储层,CP 只出计划并在 Moved 后更新 Location。
	TriggerDefrag(context.Context, *TriggerDefragRequest) (*TriggerDefragResponse, error)
	// 暂停/恢复共享后台带宽池(promote/demote/GC/defrag,<10%)。
	PauseBackground(context.Context, *PauseBackgroundRequest) (*Ack, error)
	// P4.9:一致性哈希分片(F11 扩缩)。单测模拟环/最小迁移/Drain;真跨机字节迁移 → P5。
	GetShardMap(context.Context, *GetShardMapRequest) (*GetShardMapResponse, error)
	// 加入 KV Node → 重算环,仅返回落在新节点区间的迁移计划(最小迁移)。
	//
	//	P7 收口(方案 Z):join 后**新节点 warmup 由池侧自主决策发起**(CP 按
	//	hit_count 选热块 → agent PlaceBlocks),Router 只报告命中(ReportHits)、
	//	不指挥放置。
	JoinShardNode(context.Context, *JoinShardNodeRequest) (*JoinShardNodeResponse, error)
	// 缩容:标记 Drain + 迁出计划 + 需先推 L2 的 block 列表(逻辑;字节迁移 P5)。
	DrainShardNode(context.Context, *DrainShardNodeRequest) (*DrainShardNodeResponse, error)
	// Drain 完成后从环移除(无剩余所有权时)。
	RemoveShardNode(context.Context, *RemoveShardNodeRequest) (*Ack, error)
	// P7 收口:命中上报(best-effort 批量)。Router 在本地镜像上观测到前缀命中后
	//
	//	批量回传,CP 累计到 radix 节点 hit_count(SGLang TreeNode.hit_count 同款),
	//	供 promote 准入 / 扩容 warmup 选块 / 未来方案 Z 预放置复用——一套热度信号。
	//	丢失可容忍(计数偏弱),不进 ViewEvent。
	ReportHits(context.Context, *ReportHitsRequest) (*Ack, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) SubscribeView(*SubscribeRequest, grpc.ServerStreamingServer[ViewUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribeView not implemented")
}
func (UnimplementedControlPlaneServiceServer) LookupPrefix(context.Context, *LookupPrefixRequest) (*LookupPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupPrefix not implemented")
}
func (UnimplementedControlPlaneServiceServer) Locate(context.Context, *LocateRequest) (*LocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Locate not implemented")
}
func (UnimplementedControlPlaneServiceServer) AdmitRegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmitRegisterBlocks not implemented")
}
func (UnimplementedControlPlaneServiceServer) RegisterBlocks(context.Context, *RegisterBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBlocks not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportRef(grpc.ClientStreamingServer[RefDelta, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportRef not implemented")
}
func (UnimplementedControlPlaneServiceServer) RequestBarrier(context.Context, *RequestBarrierRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBarrier not implemented")
}
func (UnimplementedControlPlaneServiceServer) Lease(grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]) error {
	return status.Error(codes.Unimplemented, "method Lease not implemented")
}
func (UnimplementedControlPlaneServiceServer) RegisterModel(context.Context, *RegisterModelRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModel not implemented")
}
func (UnimplementedControlPlaneServiceServer) DeregisterModel(context.Context, *DeregisterModelRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DeregisterModel not implemented")
}
func (UnimplementedControlPlaneServiceServer) SetModelQuota(context.Context, *SetModelQuotaRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SetModelQuota not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetModelQuota(context.Context, *GetModelQuotaRequest) (*GetModelQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelQuota not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReconcileOrphans(context.Context, *ReconcileOrphansRequest) (*ReconcileOrphansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileOrphans not implemented")
}
func (UnimplementedControlPlaneServiceServer) DiscardBlocks(context.Context, *DiscardBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardBlocks not implemented")
}
func (UnimplementedControlPlaneServiceServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedControlPlaneServiceServer) RestoreCheckpoint(context.Context, *RestoreCheckpointRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreCheckpoint not implemented")
}
func (UnimplementedControlPlaneServiceServer) TriggerDefrag(context.Context, *TriggerDefragRequest) (*TriggerDefragResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerDefrag not implemented")
}
func (UnimplementedControlPlaneServiceServer) PauseBackground(context.Context, *PauseBackgroundRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseBackground not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetShardMap(context.Context, *GetShardMapRequest) (*GetShardMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShardMap not implemented")
}
func (UnimplementedControlPlaneServiceServer) JoinShardNode(context.Context, *JoinShardNodeRequest) (*JoinShardNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinShardNode not implemented")
}
func (UnimplementedControlPlaneServiceServer) DrainShardNode(context.Context, *DrainShardNodeRequest) (*DrainShardNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainShardNode not implemented")
}
func (UnimplementedControlPlaneServiceServer) RemoveShardNode(context.Context, *RemoveShardNodeRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveShardNode not implemented")
}
func (UnimplementedControlPlaneServiceServer) ReportHits(context.Context, *ReportHitsRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHits not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_SubscribeView_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlPlaneServiceServer).SubscribeView(m, &grpc.GenericServerStream[SubscribeRequest, ViewUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_SubscribeViewServer = grpc.ServerStreamingServer[ViewUpdate]

func _ControlPlaneService_LookupPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).LookupPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_LookupPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).LookupPrefix(ctx, req.(*LookupPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_Locate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).Locate(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_AdmitRegisterBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).AdmitRegisterBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_AdmitRegisterBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).AdmitRegisterBlocks(ctx, req.(*RegisterBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RegisterBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterBlocks(ctx, req.(*RegisterBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportRef_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServiceServer).ReportRef(&grpc.GenericServerStream[RefDelta, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_ReportRefServer = grpc.ClientStreamingServer[RefDelta, Ack]

func _ControlPlaneService_RequestBarrier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBarrierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RequestBarrier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RequestBarrier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RequestBarrier(ctx, req.(*RequestBarrierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_Lease_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlPlaneServiceServer).Lease(&grpc.GenericServerStream[LeaseHeartbeat, LeaseAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlPlaneService_LeaseServer = grpc.BidiStreamingServer[LeaseHeartbeat, LeaseAck]

func _ControlPlaneService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RegisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RegisterModel(ctx, req.(*RegisterModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_DeregisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).DeregisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_DeregisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).DeregisterModel(ctx, req.(*DeregisterModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_SetModelQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModelQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).SetModelQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_SetModelQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).SetModelQuota(ctx, req.(*SetModelQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetModelQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetModelQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetModelQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetModelQuota(ctx, req.(*GetModelQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReconcileOrphans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileOrphansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReconcileOrphans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReconcileOrphans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReconcileOrphans(ctx, req.(*ReconcileOrphansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_DiscardBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).DiscardBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_DiscardBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).DiscardBlocks(ctx, req.(*DiscardBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RestoreCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RestoreCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RestoreCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RestoreCheckpoint(ctx, req.(*RestoreCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_TriggerDefrag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerDefragRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).TriggerDefrag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_TriggerDefrag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).TriggerDefrag(ctx, req.(*TriggerDefragRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_PauseBackground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseBackgroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).PauseBackground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_PauseBackground_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).PauseBackground(ctx, req.(*PauseBackgroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetShardMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShardMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetShardMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetShardMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetShardMap(ctx, req.(*GetShardMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_JoinShardNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinShardNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).JoinShardNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_JoinShardNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).JoinShardNode(ctx, req.(*JoinShardNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_DrainShardNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainShardNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).DrainShardNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_DrainShardNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).DrainShardNode(ctx, req.(*DrainShardNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_RemoveShardNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveShardNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).RemoveShardNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_RemoveShardNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).RemoveShardNode(ctx, req.(*RemoveShardNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ReportHits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ReportHits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ReportHits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ReportHits(ctx, req.(*ReportHitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupPrefix",
			Handler:    _ControlPlaneService_LookupPrefix_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _ControlPlaneService_Locate_Handler,
		},
		{
			MethodName: "AdmitRegisterBlocks",
			Handler:    _ControlPlaneService_AdmitRegisterBlocks_Handler,
		},
		{
			MethodName: "RegisterBlocks",
			Handler:    _ControlPlaneService_RegisterBlocks_Handler,
		},
		{
			MethodName: "RequestBarrier",
			Handler:    _ControlPlaneService_RequestBarrier_Handler,
		},
		{
			MethodName: "RegisterModel",
			Handler:    _ControlPlaneService_RegisterModel_Handler,
		},
		{
			MethodName: "DeregisterModel",
			Handler:    _ControlPlaneService_DeregisterModel_Handler,
		},
		{
			MethodName: "SetModelQuota",
			Handler:    _ControlPlaneService_SetModelQuota_Handler,
		},
		{
			MethodName: "GetModelQuota",
			Handler:    _ControlPlaneService_GetModelQuota_Handler,
		},
		{
			MethodName: "ReconcileOrphans",
			Handler:    _ControlPlaneService_ReconcileOrphans_Handler,
		},
		{
			MethodName: "DiscardBlocks",
			Handler:    _ControlPlaneService_DiscardBlocks_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _ControlPlaneService_SaveCheckpoint_Handler,
		},
		{
			MethodName: "RestoreCheckpoint",
			Handler:    _ControlPlaneService_RestoreCheckpoint_Handler,
		},
		{
			MethodName: "TriggerDefrag",
			Handler:    _ControlPlaneService_TriggerDefrag_Handler,
		},
		{
			MethodName: "PauseBackground",
			Handler:    _ControlPlaneService_PauseBackground_Handler,
		},
		{
			MethodName: "GetShardMap",
			Handler:    _ControlPlaneService_GetShardMap_Handler,
		},
		{
			MethodName: "JoinShardNode",
			Handler:    _ControlPlaneService_JoinShardNode_Handler,
		},
		{
			MethodName: "DrainShardNode",
			Handler:    _ControlPlaneService_DrainShardNode_Handler,
		},
		{
			MethodName: "RemoveShardNode",
			Handler:    _ControlPlaneService_RemoveShardNode_Handler,
		},
		{
			MethodName: "ReportHits",
			Handler:    _ControlPlaneService_ReportHits_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeView",
			Handler:       _ControlPlaneService_SubscribeView_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportRef",
			Handler:       _ControlPlaneService_ReportRef_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Lease",
			Handler:       _ControlPlaneService_Lease_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lake.proto",
}

const (
	AgentService_Dispatch_FullMethodName    = "/lake.AgentService/Dispatch"
	AgentService_ReportLoad_FullMethodName  = "/lake.AgentService/ReportLoad"
	AgentService_PlaceBlocks_FullMethodName = "/lake.AgentService/PlaceBlocks"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// AgentService — 边10:Router/控制面 → agent
// =============================================================================
type AgentServiceClient interface {
	// 边10:Router 选好模式+节点后,下发调度指令给目标 agent(组 batch)。
	//
	//	携带 hints(agent_hints/kv_hints),与 #13 Bifrost 透传对齐(仿 SGLang #21846 agent_hints)。
	//	本稿只定调度骨架;request_id / 输入 token / 采样参数等请求体字段后续 PR 补。
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Ack, error)
	// 边10:agent 上报负载(队列长度/in-flight/剩余容量),供过载信号 P7 对接 Bifrost。
	//
	//	流式上报、流式 ack(避免客户端关流才 ack 的运维别扭)。
	ReportLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoadReport, Ack], error)
	// 控制面 → agent:补拉放置(缺失 KV 放到指定节点 HBM,方案 Z 单向耦合)。
	PlaceBlocks(ctx context.Context, in *PlaceBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LoadReport, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportLoad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadReport, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportLoadClient = grpc.BidiStreamingClient[LoadReport, Ack]

func (c *agentServiceClient) PlaceBlocks(ctx context.Context, in *PlaceBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_PlaceBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// =============================================================================
// AgentService — 边10:Router/控制面 → agent
// =============================================================================
type AgentServiceServer interface {
	// 边10:Router 选好模式+节点后,下发调度指令给目标 agent(组 batch)。
	//
	//	携带 hints(agent_hints/kv_hints),与 #13 Bifrost 透传对齐(仿 SGLang #21846 agent_hints)。
	//	本稿只定调度骨架;request_id / 输入 token / 采样参数等请求体字段后续 PR 补。
	Dispatch(context.Context, *DispatchRequest) (*Ack, error)
	// 边10:agent 上报负载(队列长度/in-flight/剩余容量),供过载信号 P7 对接 Bifrost。
	//
	//	流式上报、流式 ack(避免客户端关流才 ack 的运维别扭)。
	ReportLoad(grpc.BidiStreamingServer[LoadReport, Ack]) error
	// 控制面 → agent:补拉放置(缺失 KV 放到指定节点 HBM,方案 Z 单向耦合)。
	PlaceBlocks(context.Context, *PlaceBlocksRequest) (*Ack, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Dispatch(context.Context, *DispatchRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedAgentServiceServer) ReportLoad(grpc.BidiStreamingServer[LoadReport, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedAgentServiceServer) PlaceBlocks(context.Context, *PlaceBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBlocks not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportLoad(&grpc.GenericServerStream[LoadReport, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportLoadServer = grpc.BidiStreamingServer[LoadReport, Ack]

func _AgentService_PlaceBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PlaceBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PlaceBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PlaceBlocks(ctx, req.(*PlaceBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _AgentService_Dispatch_Handler,
		},
		{
			MethodName: "PlaceBlocks",
			Handler:    _AgentService_PlaceBlocks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportLoad",
			Handler:       _AgentService_ReportLoad_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lake.proto",
}

const (
	TransferService_SubmitTransfer_FullMethodName    = "/lake.TransferService/SubmitTransfer"
	TransferService_GetTransferStatus_FullMethodName = "/lake.TransferService/GetTransferStatus"
	TransferService_FreeBatch_FullMethodName         = "/lake.TransferService/FreeBatch"
	TransferService_Pull_FullMethodName              = "/lake.TransferService/Pull"
	TransferService_FreePull_FullMethodName          = "/lake.TransferService/FreePull"
	TransferService_Publish_FullMethodName           = "/lake.TransferService/Publish"
	TransferService_FreePublish_FullMethodName       = "/lake.TransferService/FreePublish"
)

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// TransferService — 边7/8:传输控制信令(字节走数据面旁路)
// =============================================================================
// P4.4:接线 TcpTransport(单进程本地拷贝 / gRPC TcpDataService 字节搬运)。
// P5:同 API 换 RdmaTransport(Mooncake FFI),业务零改。
type TransferServiceClient interface {
	// 仿 Mooncake TransferEngine:
	//
	//	allocateBatchID → submitTransfer(batch,{TransferRequest}) → getTransferStatus → freeBatchID。
	//
	// SubmitTransfer = allocate + submit(返回 batch_id);task_id = 批内下标。
	// 调用方查完 status 后须 FreeBatch(对齐 Mooncake freeBatchID),否则 batches 表泄漏。
	SubmitTransfer(ctx context.Context, in *TransferBatchRequest, opts ...grpc.CallOption) (*TransferBatchAck, error)
	GetTransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error)
	FreeBatch(ctx context.Context, in *FreeBatchRequest, opts ...grpc.CallOption) (*Ack, error)
	// 引擎契约:pull(block_ids) 返回 handle,publish(逐层增量)上报产出。
	//
	//	跨实例控制信令;worker 本机调 agent 走 FFI(边6)不进 proto。
	//	Pull 异步 + 可中断(仿 SGLang prefetch 三策略 + 预算);Publish layer-wise(仿 SGLang on_publish + page_first_direct)。
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error)
	// 释放 Pull handle + 其目标段(TcpTransport arena);不调用则 handle/段按 Pull 次数泄漏。
	FreePull(ctx context.Context, in *FreePullRequest, opts ...grpc.CallOption) (*Ack, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error)
	// 释放某 request_id 的 PublishStream(seq fence + layer 累计);对齐 FreeBatch 生命周期。
	//
	//	不调用则按请求数常驻增长(复审 should-fix)。请求结束 / barrier 后应调一次。
	FreePublish(ctx context.Context, in *FreePublishRequest, opts ...grpc.CallOption) (*Ack, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) SubmitTransfer(ctx context.Context, in *TransferBatchRequest, opts ...grpc.CallOption) (*TransferBatchAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBatchAck)
	err := c.cc.Invoke(ctx, TransferService_SubmitTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) GetTransferStatus(ctx context.Context, in *TransferStatusRequest, opts ...grpc.CallOption) (*TransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferStatusResponse)
	err := c.cc.Invoke(ctx, TransferService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) FreeBatch(ctx context.Context, in *FreeBatchRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TransferService_FreeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*PullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullResponse)
	err := c.cc.Invoke(ctx, TransferService_Pull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) FreePull(ctx context.Context, in *FreePullRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TransferService_FreePull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TransferService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) FreePublish(ctx context.Context, in *FreePublishRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TransferService_FreePublish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility.
//
// =============================================================================
// TransferService — 边7/8:传输控制信令(字节走数据面旁路)
// =============================================================================
// P4.4:接线 TcpTransport(单进程本地拷贝 / gRPC TcpDataService 字节搬运)。
// P5:同 API 换 RdmaTransport(Mooncake FFI),业务零改。
type TransferServiceServer interface {
	// 仿 Mooncake TransferEngine:
	//
	//	allocateBatchID → submitTransfer(batch,{TransferRequest}) → getTransferStatus → freeBatchID。
	//
	// SubmitTransfer = allocate + submit(返回 batch_id);task_id = 批内下标。
	// 调用方查完 status 后须 FreeBatch(对齐 Mooncake freeBatchID),否则 batches 表泄漏。
	SubmitTransfer(context.Context, *TransferBatchRequest) (*TransferBatchAck, error)
	GetTransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error)
	FreeBatch(context.Context, *FreeBatchRequest) (*Ack, error)
	// 引擎契约:pull(block_ids) 返回 handle,publish(逐层增量)上报产出。
	//
	//	跨实例控制信令;worker 本机调 agent 走 FFI(边6)不进 proto。
	//	Pull 异步 + 可中断(仿 SGLang prefetch 三策略 + 预算);Publish layer-wise(仿 SGLang on_publish + page_first_direct)。
	Pull(context.Context, *PullRequest) (*PullResponse, error)
	// 释放 Pull handle + 其目标段(TcpTransport arena);不调用则 handle/段按 Pull 次数泄漏。
	FreePull(context.Context, *FreePullRequest) (*Ack, error)
	Publish(context.Context, *PublishRequest) (*Ack, error)
	// 释放某 request_id 的 PublishStream(seq fence + layer 累计);对齐 FreeBatch 生命周期。
	//
	//	不调用则按请求数常驻增长(复审 should-fix)。请求结束 / barrier 后应调一次。
	FreePublish(context.Context, *FreePublishRequest) (*Ack, error)
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferServiceServer struct{}

func (UnimplementedTransferServiceServer) SubmitTransfer(context.Context, *TransferBatchRequest) (*TransferBatchAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTransfer not implemented")
}
func (UnimplementedTransferServiceServer) GetTransferStatus(context.Context, *TransferStatusRequest) (*TransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedTransferServiceServer) FreeBatch(context.Context, *FreeBatchRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method FreeBatch not implemented")
}
func (UnimplementedTransferServiceServer) Pull(context.Context, *PullRequest) (*PullResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedTransferServiceServer) FreePull(context.Context, *FreePullRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method FreePull not implemented")
}
func (UnimplementedTransferServiceServer) Publish(context.Context, *PublishRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedTransferServiceServer) FreePublish(context.Context, *FreePublishRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method FreePublish not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}
func (UnimplementedTransferServiceServer) testEmbeddedByValue()                         {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	// If the following call panics, it indicates UnimplementedTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_SubmitTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).SubmitTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_SubmitTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).SubmitTransfer(ctx, req.(*TransferBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, req.(*TransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_FreeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreeBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).FreeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_FreeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).FreeBatch(ctx, req.(*FreeBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_FreePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).FreePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_FreePull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).FreePull(ctx, req.(*FreePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_FreePublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreePublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).FreePublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_FreePublish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).FreePublish(ctx, req.(*FreePublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransfer",
			Handler:    _TransferService_SubmitTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _TransferService_GetTransferStatus_Handler,
		},
		{
			MethodName: "FreeBatch",
			Handler:    _TransferService_FreeBatch_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _TransferService_Pull_Handler,
		},
		{
			MethodName: "FreePull",
			Handler:    _TransferService_FreePull_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _TransferService_Publish_Handler,
		},
		{
			MethodName: "FreePublish",
			Handler:    _TransferService_FreePublish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lake.proto",
}

const (
	TcpDataService_PutBlocks_FullMethodName = "/lake.TcpDataService/PutBlocks"
	TcpDataService_GetBlocks_FullMethodName = "/lake.TcpDataService/GetBlocks"
)

// TcpDataServiceClient is the client API for TcpDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// TcpDataService — TCP 退化数据面(P4.4 正名自 P3 SkeletonKvService)
// =============================================================================
//
// 对齐 Mooncake `MC_FORCE_TCP` / `installTransport("tcp")` fallback:
//
//	无 RDMA 时 KV **字节**走 gRPC Put/Get(CPU 拷贝,非零拷贝)。
//	TransferService 控制信令 + TcpTransport 可经本 service 搬字节;
//	P5 真 RDMA 旁路后本 service 仍作 TCP 退化路径保留。
type TcpDataServiceClient interface {
	PutBlocks(ctx context.Context, in *PutBlocksRequest, opts ...grpc.CallOption) (*Ack, error)
	GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
}

type tcpDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTcpDataServiceClient(cc grpc.ClientConnInterface) TcpDataServiceClient {
	return &tcpDataServiceClient{cc}
}

func (c *tcpDataServiceClient) PutBlocks(ctx context.Context, in *PutBlocksRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, TcpDataService_PutBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcpDataServiceClient) GetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, TcpDataService_GetBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpDataServiceServer is the server API for TcpDataService service.
// All implementations must embed UnimplementedTcpDataServiceServer
// for forward compatibility.
//
// =============================================================================
// TcpDataService — TCP 退化数据面(P4.4 正名自 P3 SkeletonKvService)
// =============================================================================
//
// 对齐 Mooncake `MC_FORCE_TCP` / `installTransport("tcp")` fallback:
//
//	无 RDMA 时 KV **字节**走 gRPC Put/Get(CPU 拷贝,非零拷贝)。
//	TransferService 控制信令 + TcpTransport 可经本 service 搬字节;
//	P5 真 RDMA 旁路后本 service 仍作 TCP 退化路径保留。
type TcpDataServiceServer interface {
	PutBlocks(context.Context, *PutBlocksRequest) (*Ack, error)
	GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	mustEmbedUnimplementedTcpDataServiceServer()
}

// UnimplementedTcpDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTcpDataServiceServer struct{}

func (UnimplementedTcpDataServiceServer) PutBlocks(context.Context, *PutBlocksRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBlocks not implemented")
}
func (UnimplementedTcpDataServiceServer) GetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlocks not implemented")
}
func (UnimplementedTcpDataServiceServer) mustEmbedUnimplementedTcpDataServiceServer() {}
func (UnimplementedTcpDataServiceServer) testEmbeddedByValue()                        {}

// UnsafeTcpDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcpDataServiceServer will
// result in compilation errors.
type UnsafeTcpDataServiceServer interface {
	mustEmbedUnimplementedTcpDataServiceServer()
}

func RegisterTcpDataServiceServer(s grpc.ServiceRegistrar, srv TcpDataServiceServer) {
	// If the following call panics, it indicates UnimplementedTcpDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TcpDataService_ServiceDesc, srv)
}

func _TcpDataService_PutBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpDataServiceServer).PutBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TcpDataService_PutBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpDataServiceServer).PutBlocks(ctx, req.(*PutBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TcpDataService_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpDataServiceServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TcpDataService_GetBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpDataServiceServer).GetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TcpDataService_ServiceDesc is the grpc.ServiceDesc for TcpDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TcpDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.TcpDataService",
	HandlerType: (*TcpDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutBlocks",
			Handler:    _TcpDataService_PutBlocks_Handler,
		},
		{
			MethodName: "GetBlocks",
			Handler:    _TcpDataService_GetBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lake.proto",
}

const (
	WorkerService_Generate_FullMethodName = "/lake.WorkerService/Generate"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService — 计算层 Generate。
//
//	生产:Router Dispatch(边10)→ agent → FFI(边6)调引擎;token 流经 agent/SSE 回 Router。
//	P3/P4:Router 先 AgentService.Dispatch(ack 占位)再调本 service;worker 内调 ControlPlane + TcpDataService。
//	    执行仍在本 service(非 agent 组 batch);prefill/decode 同进程 mock;
//	    P6.3 起 mode 由 Router 读镜像决策后经 GenerateRequest.exec_mode 下发。
type WorkerServiceClient interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, WorkerService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService — 计算层 Generate。
//
//	生产:Router Dispatch(边10)→ agent → FFI(边6)调引擎;token 流经 agent/SSE 回 Router。
//	P3/P4:Router 先 AgentService.Dispatch(ack 占位)再调本 service;worker 内调 ControlPlane + TcpDataService。
//	    执行仍在本 service(非 agent 组 batch);prefill/decode 同进程 mock;
//	    P6.3 起 mode 由 Router 读镜像决策后经 GenerateRequest.exec_mode 下发。
type WorkerServiceServer interface {
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lake.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _WorkerService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lake.proto",
}
