// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: schema.proto

package lakepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	Tier_L0               Tier = 1 // GPU HBM(易失缓存)
	Tier_L1               Tier = 2 // DRAM 池化(易失缓存)
	Tier_L2               Tier = 3 // NVMe 池化(F4 恢复点,durable)
	Tier_L3               Tier = 4 // 对象存储(SSOT 永久权威,不进 Location,用 l3_present)
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "L0",
		2: "L1",
		3: "L2",
		4: "L3",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"L0":               1,
		"L1":               2,
		"L2":               3,
		"L3":               4,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type PoolKind int32

const (
	PoolKind_POOL_UNSPECIFIED PoolKind = 0
	PoolKind_TARGET           PoolKind = 1 // target 模型 KV
	PoolKind_DRAFT            PoolKind = 2 // draft 模型 KV(同款 schema,随 target 迁移/跨请求复用)
)

// Enum value maps for PoolKind.
var (
	PoolKind_name = map[int32]string{
		0: "POOL_UNSPECIFIED",
		1: "TARGET",
		2: "DRAFT",
	}
	PoolKind_value = map[string]int32{
		"POOL_UNSPECIFIED": 0,
		"TARGET":           1,
		"DRAFT":            2,
	}
)

func (x PoolKind) Enum() *PoolKind {
	p := new(PoolKind)
	*p = x
	return p
}

func (x PoolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[1].Descriptor()
}

func (PoolKind) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[1]
}

func (x PoolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolKind.Descriptor instead.
func (PoolKind) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

type BlockKind int32

const (
	BlockKind_KIND_UNSPECIFIED BlockKind = 0
	BlockKind_T_TYPE           BlockKind = 1 // 逐 token 完整 KV(full attention / MLA)
	BlockKind_R_TYPE_STATE     BlockKind = 2 // Mamba/state-space/卷积 recurrent state 快照
	BlockKind_R_TYPE_TRAILING  BlockKind = 3 // sliding window trailing pages
)

// Enum value maps for BlockKind.
var (
	BlockKind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "T_TYPE",
		2: "R_TYPE_STATE",
		3: "R_TYPE_TRAILING",
	}
	BlockKind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"T_TYPE":           1,
		"R_TYPE_STATE":     2,
		"R_TYPE_TRAILING":  3,
	}
)

func (x BlockKind) Enum() *BlockKind {
	p := new(BlockKind)
	*p = x
	return p
}

func (x BlockKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockKind) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[2].Descriptor()
}

func (BlockKind) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[2]
}

func (x BlockKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockKind.Descriptor instead.
func (BlockKind) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

// KVBlockID — block 身份(内容寻址 + 前缀链式哈希)
// block = page:128 token × 全部层,page-first 连续(见 kv-cache-pool.md「分块流水线」)。
//
//	身份按 token 段(page)而非按层——block_hash 本就 layer-agnostic(链式哈希只吃 token),
//	layer_idx 不进身份,只在 LayerSlice(子块传输切片)里出现。对齐 SGLang radix(每页一 hash 当 L3 key)、
//	vLLM prefix caching(token-based hash 跨层共享)。
type KVBlockID struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ModelId   string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`       // 模型命名空间
	BlockHash []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // 链式哈希 = hash(parent_block_hash || 本块 token_ids);
	// 序列起点块 parent = ⊥(空)。相同前缀 → 相同链式 hash → 命中同一 KV
	// 算法可插拔(BLAKE3-128 / SHA-256-128 / SHA-256-256),由模型注册元数据声明,
	// proto 只规定 ≥128-bit + 链式。不同 model_id 可用不同算法。
	PoolKind      PoolKind `protobuf:"varint,3,opt,name=pool_kind,json=poolKind,proto3,enum=lake.PoolKind" json:"pool_kind,omitempty"` // TARGET | DRAFT 命名空间(draft KV 同款 schema,靠字段区分,不物理分池)
	Scope         string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                                           // 多租户预留,默认 "public",当前不入寻址(F8 远期启用时改寻址语义不改结构)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVBlockID) Reset() {
	*x = KVBlockID{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVBlockID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVBlockID) ProtoMessage() {}

func (x *KVBlockID) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVBlockID.ProtoReflect.Descriptor instead.
func (*KVBlockID) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *KVBlockID) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *KVBlockID) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *KVBlockID) GetPoolKind() PoolKind {
	if x != nil {
		return x.PoolKind
	}
	return PoolKind_POOL_UNSPECIFIED
}

func (x *KVBlockID) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// Location — 单层一个物理位置(仅 L0/L1/L2 段式位置;L3 不进此处)
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tier  Tier                   `protobuf:"varint,1,opt,name=tier,proto3,enum=lake.Tier" json:"tier,omitempty"` // **硬约束:∈ {L0, L1, L2}**;L3 永不进 Location,只由 l3_present 表达。
	// Tier 枚举含 L3 仅为四层模型概念完整;生成代码/校验须拒绝 tier=L3。
	NodeId        string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`           // 载体节点(compute-X / kvnode-Y)
	SegmentId     uint64 `protobuf:"varint,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"` // 传输引擎注册段 ID(仿 Mooncake SegmentID;uint64 走传输热路径)
	Offset        uint64 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                        // 段内偏移
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *Location) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Location) GetSegmentId() uint64 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *Location) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// BlockMeta — 一个 block 的元数据(权威在存储控制面进程内存,etcd 只存降频 checkpoint)
type BlockMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KVBlockID             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlockKind     BlockKind              `protobuf:"varint,2,opt,name=block_kind,json=blockKind,proto3,enum=lake.BlockKind" json:"block_kind,omitempty"` // T_TYPE | R_TYPE_STATE | R_TYPE_TRAILING
	Locations     []*Location            `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`                                       // L0?/L1?/L2? —— 缓存副本(L0/L1 易失) + L2 durable(F4 恢复点)
	L3Present     bool                   `protobuf:"varint,4,opt,name=l3_present,json=l3Present,proto3" json:"l3_present,omitempty"`                     // L3(SSOT) 是否有副本;object key = s3://lake/kv/{model_id}/{block_hash} 现场拼,不存储
	RefCount      uint32                 `protobuf:"varint,5,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`                        // 全局引用汇总
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMeta) Reset() {
	*x = BlockMeta{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMeta) ProtoMessage() {}

func (x *BlockMeta) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMeta.ProtoReflect.Descriptor instead.
func (*BlockMeta) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *BlockMeta) GetId() *KVBlockID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BlockMeta) GetBlockKind() BlockKind {
	if x != nil {
		return x.BlockKind
	}
	return BlockKind_KIND_UNSPECIFIED
}

func (x *BlockMeta) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *BlockMeta) GetL3Present() bool {
	if x != nil {
		return x.L3Present
	}
	return false
}

func (x *BlockMeta) GetRefCount() uint32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\x12\x04lake\"\x88\x01\n" +
	"\tKVBlockID\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12+\n" +
	"\tpool_kind\x18\x03 \x01(\x0e2\x0e.lake.PoolKindR\bpoolKind\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"z\n" +
	"\bLocation\x12\x1e\n" +
	"\x04tier\x18\x01 \x01(\x0e2\n" +
	".lake.TierR\x04tier\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\x04R\tsegmentId\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x04R\x06offset\"\xc6\x01\n" +
	"\tBlockMeta\x12\x1f\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.lake.KVBlockIDR\x02id\x12.\n" +
	"\n" +
	"block_kind\x18\x02 \x01(\x0e2\x0f.lake.BlockKindR\tblockKind\x12,\n" +
	"\tlocations\x18\x03 \x03(\v2\x0e.lake.LocationR\tlocations\x12\x1d\n" +
	"\n" +
	"l3_present\x18\x04 \x01(\bR\tl3Present\x12\x1b\n" +
	"\tref_count\x18\x05 \x01(\rR\brefCount*<\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02L0\x10\x01\x12\x06\n" +
	"\x02L1\x10\x02\x12\x06\n" +
	"\x02L2\x10\x03\x12\x06\n" +
	"\x02L3\x10\x04*7\n" +
	"\bPoolKind\x12\x14\n" +
	"\x10POOL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06TARGET\x10\x01\x12\t\n" +
	"\x05DRAFT\x10\x02*T\n" +
	"\tBlockKind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06T_TYPE\x10\x01\x12\x10\n" +
	"\fR_TYPE_STATE\x10\x02\x12\x13\n" +
	"\x0fR_TYPE_TRAILING\x10\x03B)Z'github.com/chengda-wu/lake/go/pb;lakepbb\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_proto_goTypes = []any{
	(Tier)(0),         // 0: lake.Tier
	(PoolKind)(0),     // 1: lake.PoolKind
	(BlockKind)(0),    // 2: lake.BlockKind
	(*KVBlockID)(nil), // 3: lake.KVBlockID
	(*Location)(nil),  // 4: lake.Location
	(*BlockMeta)(nil), // 5: lake.BlockMeta
}
var file_schema_proto_depIdxs = []int32{
	1, // 0: lake.KVBlockID.pool_kind:type_name -> lake.PoolKind
	0, // 1: lake.Location.tier:type_name -> lake.Tier
	3, // 2: lake.BlockMeta.id:type_name -> lake.KVBlockID
	2, // 3: lake.BlockMeta.block_kind:type_name -> lake.BlockKind
	4, // 4: lake.BlockMeta.locations:type_name -> lake.Location
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
