# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lake_pb import lake_pb2 as lake__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lake_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneServiceStub:
    """RPC 边界草稿（#3 通信边 + 00-plan.md:167 三组接口）。

    原则:KV 字节走 RDMA 旁路(边7/8),proto 只定义控制 msg(查询/命令/元数据/完成回执)。
    worker ↔ in-process agent 同进程走 FFI(边6,PyO3),不进 proto。

    3 个 service 按通信边划分:
    ControlPlaneService — 边3/4/5:Router+agent ↔ 存储控制面(控制面进程实现)
    AgentService        — 边10:Router/控制面 → agent(agent 进程实现)
    TransferService     — 边7/8:RDMA 传输的控制信令(数据旁路;**agent / KV Node agent 实现,非控制面**)

    参考:
    - Dynamo protocols.rs::RouterRequest/RouterResponse/Placement(路由协议 + 命中量化)
    - vLLM KVConnectorBase_V1(worker↔池接入点、异步作业 submit_load/store/get_finished、layer-wise)
    - Mooncake transfer-engine(allocateBatchID/submitTransfer/getTransferStatus)+ store(PutStart/PutEnd 两阶段、MountSegment/lease)
    - SGLang match_prefix(LookupPrefix 蓝本)+ prefetch 三策略(Pull 预算/可中断)+ on_publish layer-wise + agent_hints(Dispatch)

    =============================================================================
    ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeView = channel.unary_stream(
                '/lake.ControlPlaneService/SubscribeView',
                request_serializer=lake__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=lake__pb2.ViewUpdate.FromString,
                _registered_method=True)
        self.LookupPrefix = channel.unary_unary(
                '/lake.ControlPlaneService/LookupPrefix',
                request_serializer=lake__pb2.LookupPrefixRequest.SerializeToString,
                response_deserializer=lake__pb2.LookupPrefixResponse.FromString,
                _registered_method=True)
        self.Locate = channel.unary_unary(
                '/lake.ControlPlaneService/Locate',
                request_serializer=lake__pb2.LocateRequest.SerializeToString,
                response_deserializer=lake__pb2.LocateResponse.FromString,
                _registered_method=True)
        self.RegisterBlocks = channel.unary_unary(
                '/lake.ControlPlaneService/RegisterBlocks',
                request_serializer=lake__pb2.RegisterBlocksRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)
        self.RequestBarrier = channel.unary_unary(
                '/lake.ControlPlaneService/RequestBarrier',
                request_serializer=lake__pb2.RequestBarrierRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)
        self.Lease = channel.stream_stream(
                '/lake.ControlPlaneService/Lease',
                request_serializer=lake__pb2.LeaseHeartbeat.SerializeToString,
                response_deserializer=lake__pb2.LeaseAck.FromString,
                _registered_method=True)


class ControlPlaneServiceServicer:
    """RPC 边界草稿（#3 通信边 + 00-plan.md:167 三组接口）。

    原则:KV 字节走 RDMA 旁路(边7/8),proto 只定义控制 msg(查询/命令/元数据/完成回执)。
    worker ↔ in-process agent 同进程走 FFI(边6,PyO3),不进 proto。

    3 个 service 按通信边划分:
    ControlPlaneService — 边3/4/5:Router+agent ↔ 存储控制面(控制面进程实现)
    AgentService        — 边10:Router/控制面 → agent(agent 进程实现)
    TransferService     — 边7/8:RDMA 传输的控制信令(数据旁路;**agent / KV Node agent 实现,非控制面**)

    参考:
    - Dynamo protocols.rs::RouterRequest/RouterResponse/Placement(路由协议 + 命中量化)
    - vLLM KVConnectorBase_V1(worker↔池接入点、异步作业 submit_load/store/get_finished、layer-wise)
    - Mooncake transfer-engine(allocateBatchID/submitTransfer/getTransferStatus)+ store(PutStart/PutEnd 两阶段、MountSegment/lease)
    - SGLang match_prefix(LookupPrefix 蓝本)+ prefetch 三策略(Pull 预算/可中断)+ on_publish layer-wise + agent_hints(Dispatch)

    =============================================================================
    ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
    =============================================================================
    """

    def SubscribeView(self, request, context):
        """边3/4:订阅位置视图 live 镜像(Router 与 agent 同协议、不同订阅者,#3 已定)。
        事件形态参考 vLLM BlockStored/BlockRemoved、Mooncake Conductor 订阅事件。
        单权威 → 单流 sequence + gap replay(见 control-plane.md「粒度与协议」)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupPrefix(self, request, context):
        """Router 选路查询:输入 (model_id, 前缀 block hashes),输出可复用 block 列表 + 位置 + 本地命中。
        **非热路径常态**——热路径 Router 在本地位置视图镜像上 match(零 RPC,见 B3)。
        本 RPC 是**权威回退**:冷启动 / 镜像 gap / 调试时查控制面权威树(与 Locate 同档,线性一致)。
        仿 SGLang match_prefix 的集群版。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Locate(self, request, context):
        """agent 搬 KV:同步查权威树(线性一致)。常态走镜像/本地 slot 不查,仅镜像不可信时查
        (见 kv-cache-pool.md「搬 KV 查权威分层」)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterBlocks(self, request, context):
        """满块注册:**耐久性由 agent 本地完成**(写 L2 durable)后,只调一次本 RPC = PutEnd。
        PutStart 不进控制面(agent 本地记账即可),防半块被读。仿 Mooncake PutEnd 的控制面侧。
        release 一致,写控制面内存,不进 etcd。
        与 Publish 的区别:Publish(可多次、逐层 slice)只更新位置视图;RegisterBlocks(满块 + L2 durable)才进 radix + 置 l3_present/L2。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestBarrier(self, request, context):
        """请求结束屏障:release → flush L2 + ack → 控制面更新目录(见 consistency.md §3)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lease(self, request_iterator, context):
        """lease:节点 mount/unmount segment + 续命(仿 Mooncake MountSegment/UnmountSegment + client_live_ttl_sec)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeView': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeView,
                    request_deserializer=lake__pb2.SubscribeRequest.FromString,
                    response_serializer=lake__pb2.ViewUpdate.SerializeToString,
            ),
            'LookupPrefix': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupPrefix,
                    request_deserializer=lake__pb2.LookupPrefixRequest.FromString,
                    response_serializer=lake__pb2.LookupPrefixResponse.SerializeToString,
            ),
            'Locate': grpc.unary_unary_rpc_method_handler(
                    servicer.Locate,
                    request_deserializer=lake__pb2.LocateRequest.FromString,
                    response_serializer=lake__pb2.LocateResponse.SerializeToString,
            ),
            'RegisterBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBlocks,
                    request_deserializer=lake__pb2.RegisterBlocksRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
            'RequestBarrier': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestBarrier,
                    request_deserializer=lake__pb2.RequestBarrierRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
            'Lease': grpc.stream_stream_rpc_method_handler(
                    servicer.Lease,
                    request_deserializer=lake__pb2.LeaseHeartbeat.FromString,
                    response_serializer=lake__pb2.LeaseAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lake.ControlPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lake.ControlPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlaneService:
    """RPC 边界草稿（#3 通信边 + 00-plan.md:167 三组接口）。

    原则:KV 字节走 RDMA 旁路(边7/8),proto 只定义控制 msg(查询/命令/元数据/完成回执)。
    worker ↔ in-process agent 同进程走 FFI(边6,PyO3),不进 proto。

    3 个 service 按通信边划分:
    ControlPlaneService — 边3/4/5:Router+agent ↔ 存储控制面(控制面进程实现)
    AgentService        — 边10:Router/控制面 → agent(agent 进程实现)
    TransferService     — 边7/8:RDMA 传输的控制信令(数据旁路;**agent / KV Node agent 实现,非控制面**)

    参考:
    - Dynamo protocols.rs::RouterRequest/RouterResponse/Placement(路由协议 + 命中量化)
    - vLLM KVConnectorBase_V1(worker↔池接入点、异步作业 submit_load/store/get_finished、layer-wise)
    - Mooncake transfer-engine(allocateBatchID/submitTransfer/getTransferStatus)+ store(PutStart/PutEnd 两阶段、MountSegment/lease)
    - SGLang match_prefix(LookupPrefix 蓝本)+ prefetch 三策略(Pull 预算/可中断)+ on_publish layer-wise + agent_hints(Dispatch)

    =============================================================================
    ControlPlaneService — 边3/4/5:Router + agent ↔ 存储控制面
    =============================================================================
    """

    @staticmethod
    def SubscribeView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lake.ControlPlaneService/SubscribeView',
            lake__pb2.SubscribeRequest.SerializeToString,
            lake__pb2.ViewUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupPrefix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.ControlPlaneService/LookupPrefix',
            lake__pb2.LookupPrefixRequest.SerializeToString,
            lake__pb2.LookupPrefixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Locate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.ControlPlaneService/Locate',
            lake__pb2.LocateRequest.SerializeToString,
            lake__pb2.LocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.ControlPlaneService/RegisterBlocks',
            lake__pb2.RegisterBlocksRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestBarrier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.ControlPlaneService/RequestBarrier',
            lake__pb2.RequestBarrierRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lease(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lake.ControlPlaneService/Lease',
            lake__pb2.LeaseHeartbeat.SerializeToString,
            lake__pb2.LeaseAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub:
    """=============================================================================
    AgentService — 边10:Router/控制面 → agent
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dispatch = channel.unary_unary(
                '/lake.AgentService/Dispatch',
                request_serializer=lake__pb2.DispatchRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportLoad = channel.stream_stream(
                '/lake.AgentService/ReportLoad',
                request_serializer=lake__pb2.LoadReport.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)
        self.PlaceBlocks = channel.unary_unary(
                '/lake.AgentService/PlaceBlocks',
                request_serializer=lake__pb2.PlaceBlocksRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """=============================================================================
    AgentService — 边10:Router/控制面 → agent
    =============================================================================
    """

    def Dispatch(self, request, context):
        """边10:Router 选好模式+节点后,下发调度指令给目标 agent(组 batch)。
        携带 hints(agent_hints/kv_hints),与 #13 Bifrost 透传对齐(仿 SGLang #21846 agent_hints)。
        本稿只定调度骨架;request_id / 输入 token / 采样参数等请求体字段后续 PR 补。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportLoad(self, request_iterator, context):
        """边10:agent 上报负载(队列长度/in-flight/剩余容量),供过载信号 P7 对接 Bifrost。
        流式上报、流式 ack(避免客户端关流才 ack 的运维别扭)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBlocks(self, request, context):
        """控制面 → agent:补拉放置(缺失 KV 放到指定节点 HBM,方案 Z 单向耦合)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=lake__pb2.DispatchRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
            'ReportLoad': grpc.stream_stream_rpc_method_handler(
                    servicer.ReportLoad,
                    request_deserializer=lake__pb2.LoadReport.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
            'PlaceBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBlocks,
                    request_deserializer=lake__pb2.PlaceBlocksRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lake.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lake.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """=============================================================================
    AgentService — 边10:Router/控制面 → agent
    =============================================================================
    """

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.AgentService/Dispatch',
            lake__pb2.DispatchRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportLoad(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/lake.AgentService/ReportLoad',
            lake__pb2.LoadReport.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.AgentService/PlaceBlocks',
            lake__pb2.PlaceBlocksRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TransferServiceStub:
    """=============================================================================
    TransferService — 边7/8:RDMA 传输的控制信令(字节走 RDMA 旁路)
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTransfer = channel.unary_unary(
                '/lake.TransferService/SubmitTransfer',
                request_serializer=lake__pb2.TransferBatchRequest.SerializeToString,
                response_deserializer=lake__pb2.TransferBatchAck.FromString,
                _registered_method=True)
        self.GetTransferStatus = channel.unary_unary(
                '/lake.TransferService/GetTransferStatus',
                request_serializer=lake__pb2.TransferStatusRequest.SerializeToString,
                response_deserializer=lake__pb2.TransferStatusResponse.FromString,
                _registered_method=True)
        self.Pull = channel.unary_unary(
                '/lake.TransferService/Pull',
                request_serializer=lake__pb2.PullRequest.SerializeToString,
                response_deserializer=lake__pb2.PullResponse.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/lake.TransferService/Publish',
                request_serializer=lake__pb2.PublishRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)


class TransferServiceServicer:
    """=============================================================================
    TransferService — 边7/8:RDMA 传输的控制信令(字节走 RDMA 旁路)
    =============================================================================
    """

    def SubmitTransfer(self, request, context):
        """仿 Mooncake:allocateBatchID → submitTransfer(batch,{TransferRequest}) → getTransferStatus。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransferStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pull(self, request, context):
        """引擎契约:pull(block_ids) 返回 handle,publish(逐层增量)上报产出。
        跨实例控制信令;worker 本机调 agent 走 FFI(边6)不进 proto。
        Pull 异步 + 可中断(仿 SGLang prefetch 三策略 + 预算);Publish layer-wise(仿 SGLang on_publish + page_first_direct)。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTransfer,
                    request_deserializer=lake__pb2.TransferBatchRequest.FromString,
                    response_serializer=lake__pb2.TransferBatchAck.SerializeToString,
            ),
            'GetTransferStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransferStatus,
                    request_deserializer=lake__pb2.TransferStatusRequest.FromString,
                    response_serializer=lake__pb2.TransferStatusResponse.SerializeToString,
            ),
            'Pull': grpc.unary_unary_rpc_method_handler(
                    servicer.Pull,
                    request_deserializer=lake__pb2.PullRequest.FromString,
                    response_serializer=lake__pb2.PullResponse.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=lake__pb2.PublishRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lake.TransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lake.TransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransferService:
    """=============================================================================
    TransferService — 边7/8:RDMA 传输的控制信令(字节走 RDMA 旁路)
    =============================================================================
    """

    @staticmethod
    def SubmitTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.TransferService/SubmitTransfer',
            lake__pb2.TransferBatchRequest.SerializeToString,
            lake__pb2.TransferBatchAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransferStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.TransferService/GetTransferStatus',
            lake__pb2.TransferStatusRequest.SerializeToString,
            lake__pb2.TransferStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.TransferService/Pull',
            lake__pb2.PullRequest.SerializeToString,
            lake__pb2.PullResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.TransferService/Publish',
            lake__pb2.PublishRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SkeletonKvServiceStub:
    """=============================================================================
    P3 skeleton-only services(验证三语言联通;生产路径见上方注释)
    =============================================================================

    SkeletonKvService — mock KV **字节**走 gRPC。
    生产:字节走 RDMA 旁路(边7/8),proto 只有控制信令。
    P3:无 RDMA/PyO3 时用本 service 把不透明 bytes 写入 Rust 内存池,验证跨语言 KV 流转。
    P4 起由 TransferService + 数据面取代,本 service 可删或留 debug。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutBlocks = channel.unary_unary(
                '/lake.SkeletonKvService/PutBlocks',
                request_serializer=lake__pb2.PutBlocksRequest.SerializeToString,
                response_deserializer=lake__pb2.Ack.FromString,
                _registered_method=True)
        self.GetBlocks = channel.unary_unary(
                '/lake.SkeletonKvService/GetBlocks',
                request_serializer=lake__pb2.GetBlocksRequest.SerializeToString,
                response_deserializer=lake__pb2.GetBlocksResponse.FromString,
                _registered_method=True)


class SkeletonKvServiceServicer:
    """=============================================================================
    P3 skeleton-only services(验证三语言联通;生产路径见上方注释)
    =============================================================================

    SkeletonKvService — mock KV **字节**走 gRPC。
    生产:字节走 RDMA 旁路(边7/8),proto 只有控制信令。
    P3:无 RDMA/PyO3 时用本 service 把不透明 bytes 写入 Rust 内存池,验证跨语言 KV 流转。
    P4 起由 TransferService + 数据面取代,本 service 可删或留 debug。
    """

    def PutBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkeletonKvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.PutBlocks,
                    request_deserializer=lake__pb2.PutBlocksRequest.FromString,
                    response_serializer=lake__pb2.Ack.SerializeToString,
            ),
            'GetBlocks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlocks,
                    request_deserializer=lake__pb2.GetBlocksRequest.FromString,
                    response_serializer=lake__pb2.GetBlocksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lake.SkeletonKvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lake.SkeletonKvService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkeletonKvService:
    """=============================================================================
    P3 skeleton-only services(验证三语言联通;生产路径见上方注释)
    =============================================================================

    SkeletonKvService — mock KV **字节**走 gRPC。
    生产:字节走 RDMA 旁路(边7/8),proto 只有控制信令。
    P3:无 RDMA/PyO3 时用本 service 把不透明 bytes 写入 Rust 内存池,验证跨语言 KV 流转。
    P4 起由 TransferService + 数据面取代,本 service 可删或留 debug。
    """

    @staticmethod
    def PutBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.SkeletonKvService/PutBlocks',
            lake__pb2.PutBlocksRequest.SerializeToString,
            lake__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.SkeletonKvService/GetBlocks',
            lake__pb2.GetBlocksRequest.SerializeToString,
            lake__pb2.GetBlocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """WorkerService — 计算层 Generate。
    生产:Router Dispatch(边10)→ agent → FFI(边6)调引擎;token 流经 agent/SSE 回 Router。
    P3:Router 先 AgentService.Dispatch(ack 占位)再调本 service;worker 内调 ControlPlane + SkeletonKv。
    执行仍在本 service(非 agent 组 batch);prefill/decode 同进程 mock;**mode 固定 COLOCATED**。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/lake.WorkerService/Generate',
                request_serializer=lake__pb2.GenerateRequest.SerializeToString,
                response_deserializer=lake__pb2.GenerateResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """WorkerService — 计算层 Generate。
    生产:Router Dispatch(边10)→ agent → FFI(边6)调引擎;token 流经 agent/SSE 回 Router。
    P3:Router 先 AgentService.Dispatch(ack 占位)再调本 service;worker 内调 ControlPlane + SkeletonKv。
    执行仍在本 service(非 agent 组 batch);prefill/decode 同进程 mock;**mode 固定 COLOCATED**。
    """

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=lake__pb2.GenerateRequest.FromString,
                    response_serializer=lake__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lake.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lake.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """WorkerService — 计算层 Generate。
    生产:Router Dispatch(边10)→ agent → FFI(边6)调引擎;token 流经 agent/SSE 回 Router。
    P3:Router 先 AgentService.Dispatch(ack 占位)再调本 service;worker 内调 ControlPlane + SkeletonKv。
    执行仍在本 service(非 agent 组 batch);prefill/decode 同进程 mock;**mode 固定 COLOCATED**。
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lake.WorkerService/Generate',
            lake__pb2.GenerateRequest.SerializeToString,
            lake__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
